#!/usr/bin/env node
// @capability: bench-pool
// @serves: stratified benchmark candidate pool | n>=100 area-spread find set authoring input | provenance-safe answer candidates
// @does: generates the STRATIFIED CANDIDATE POOL for the owner-authored n>=100 find set
//   (owner-authorized 2026-07-28). Per balanced-menu area (135 areas, MAX_MEMBERS=400 split), up
//   to 2 answer candidates, EVENLY SPREAD across the area's path-sorted members (an alphabetical
//   head-slice systematically over-samples digits and early letters — deterministic is not the
//   same as representative). PROVENANCE GUARD: the pool contains paths, areas, kinds, and two
//   LABELS only — no serves/does text, no tag content, no descriptions.
//
//   LABELS, NOT FILTERS (Hermes construct-validity ruling 2026-07-28): fts_reachable and
//   basename_unique were briefly HARD FILTERS, which made a question whose answer BM25 cannot
//   reach structurally unaskable — a guaranteed 100% coverage ceiling for every lexical arm and
//   a benchmark pruned to winnable items, exactly what retrieval-validation-gates.md forbids
//   ('keep questions the system cannot currently win when they mark a real blind spot'). A file
//   missing from the index is a REAL navigation failure and must remain askable; a colliding
//   basename is where navigation is HARD, and the remedy is a more precise expect, not deleting
//   the question. Both are now emitted as annotations so the author can include blind spots
//   DELIBERATELY. Remaining hard filters, and why each passes the legitimate-vs-fraud test
//   without reference to what the system can currently do: existingAnswers (avoids duplicating
//   find-40) and PROTECTED_PREFIXES (protected paths are never valid answers).
//
//   STRATIFICATION JUSTIFICATION (corpus statistics alone): the balanced-menu areas are a
//   directory-derived partition chosen because 88% of corpus mass sat in two dir1 blobs — a
//   degenerate layout by mass, independent of any benchmark. CAVEAT: the pool's strata are the
//   axes of a navigation design that is itself under measurement; a future non-directory-aligned
//   design would be measured on a set laid out along this one's axes.
//   SEPARATION: question AUTHORING is an owner judgment (yuri-origin Loop Discipline); this tool
//   only stratifies the corpus so the authored set can be area-spread rather than 87.5% in one
//   tree like find-40 (measured: 35/40 answers in the _SYSTEM tree).
// @use: node bench-pool.mjs [--json] [--per-area=2]   -> writes _SYSTEM/state/atlas/bench-pool.json
// @exports: buildPool, main

import { readFileSync, writeFileSync, existsSync, realpathSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const BENCHMARK = path.join(REPO_ROOT, '_SYSTEM/eval/atlas-benchmark.jsonl');
const INDEX_DB = path.join(REPO_ROOT, '_SYSTEM/OS_KERNEL/search-index.db');
const OUT_PATH = path.join(REPO_ROOT, '_SYSTEM/state/atlas/bench-pool.json');
const REJECTED_PATH = path.join(REPO_ROOT, '_SYSTEM/state/atlas/bench-pool-rejected.json');

// PROTECTED SET (canonical floor + repo extras, Hermes 2026-07-28 rebuild order). DOCTRINE
// BOUNDARY, stated so nobody "fixes" this by loosening it: protected paths are MUTATION-locked,
// not unreadable — everything inside yuri is readable (Marcel's standing ruling). They are
// excluded from the benchmark pool because a navigation question whose ANSWER is a volatile
// state file, a credential-shaped path, or generated bulk data is a bad question, not because
// reading them is forbidden.
const PROTECTED_PREFIXES = [
  '.env',
  'node_modules/',
  'backend/data/',
  '_SYSTEM/backend/data/', // repo extra: the catalog actually lives under _SYSTEM (lane-kernel's root-only list missed it)
  '_SYSTEM/state/', // loop bulk: whatsapp-cache, mcs-test shards, generated atlas artifacts — volatile runtime state is a bad ANSWER (matches the extractor's standing exclusion)
  '.amp/',
  '.git/',
  '.claude/state/',
  '.claude/history/',
  '.claude/file-history/',
  '.claude/projects/', // covers */{history,state,file-history,worktrees,transcripts}
];
// Secret-shaped FILE patterns (never a valid answer). Matches credential material by shape —
// extensions, well-known key names, secrets stores — NOT the topic word 'secret' alone (a
// secret-leak SCANNER is a defensive tool and a legitimate navigation answer).
const SECRET_NAME_RE = /(^|\/)(id_rsa|id_dsa|id_ecdsa|id_ed25519|credentials?|secrets?)(\.|$)|\.(pem|key|p12|pfx|keystore|jks)$/i;

// VOLATILE-GENERATED rail (Hermes 2026-07-28 _SYSTEM/data test, file-level split): generated by
// a process AND churns without a navigation decision. A DISTINCT rail from protected-prefix —
// keep the reasons separate in the manifest or it becomes unreviewable. Formula banks (.v0,
// authored, versioned) and the curated osv snapshot are INCLUDED by the same test.
const VOLATILE_GENERATED = [
  { match: (rel) => rel.startsWith('_SYSTEM/data/cyber-intel/'), why: 'proof/replay matrix artifacts with live generators (cyber-*.mjs) and generatedAt stamps — content changes when a proof run reruns' },
  // mechanism-pattern-registry.json checked and INCLUDED (advisory 2026-07-28): no generator
  // exists, read-only closed v0 taxonomy, owner-promoted — fails the generated+churn test.
];

export async function buildPool({ perArea = 2 } = {}) {
  const menuMod = await import('./atlas-menu.mjs');
  const menu = menuMod.loadMenu();
  const nodes = menu.l1.nodes;

  const existingAnswers = new Set(
    readFileSync(BENCHMARK, 'utf8').trim().split('\n').map((l) => {
      const j = JSON.parse(l);
      return (j.expect || []).map((e) => String(e).replace(/^\.\//, '').replace(/\/+$/, ''));
    }).flat(),
  );

  // Basename uniqueness across the id-map (ambiguity = unanswerable).
  const basenameCount = new Map();
  for (const node of Object.values(nodes)) {
    if (!node || typeof node.path !== 'string') continue;
    const base = path.basename(node.path);
    basenameCount.set(base, (basenameCount.get(base) || 0) + 1);
  }

  // FTS reachability (the scorer's substrate).
  const { default: Database } = await import('better-sqlite3');
  const db = new Database(INDEX_DB, { readonly: true });
  const ftsPaths = new Set(db.prepare('SELECT path FROM docs').all().map((r) => r.path));
  db.close();

  const pool = [];
  const rejected = []; // REJECTION MANIFEST — per-path reason, or a filter with no log did nothing
  const perAreaStats = [];
  let excludedExisting = 0;
  let labeledUnreachable = 0;
  let labeledNonUnique = 0;
  const reject = (p, reason) => rejected.push({ path: p, reason });
  // REALPATH-BEFORE-MATCH, fail-closed: resolve the root ONCE (abort the build if it cannot
  // resolve — never fall back to a lexical root), resolve each candidate FIRST, require
  // containment, and ONLY THEN classify the RESOLVED repo-relative path. A symlink cannot walk
  // a candidate past the filter because the filter never sees the lexical path.
  const isProtectedRel = (rel) => PROTECTED_PREFIXES.some((pre) => rel === pre.replace(/\/$/, '') || rel.startsWith(pre));
  const realRoot = realpathSync(REPO_ROOT); // throws -> buildPool rejects, fail closed
  for (const area of [...menu.areas].sort((a, b) => b.members - a.members || a.id.localeCompare(b.id))) {
    const candidates = [];
    for (const memberId of area.memberIds) {
      const node = nodes[memberId];
      if (!node || typeof node.path !== 'string') continue;
      const p = node.path;
      const norm = p.replace(/^\.\//, '').replace(/\/+$/, '');
      if (existingAnswers.has(norm)) { excludedExisting++; reject(norm, 'existing-answer: duplicates find-40'); continue; }
      let realAbs;
      try { realAbs = realpathSync(path.join(REPO_ROOT, norm)); } catch { reject(norm, 'unresolvable: realpath failed (dangling symlink or missing file)'); continue; }
      if (realAbs !== realRoot && !realAbs.startsWith(realRoot + path.sep)) { reject(norm, `symlink-escape: resolves outside repo to ${realAbs}`); continue; }
      const resolvedRel = path.relative(realRoot, realAbs).replace(/\\/g, '/');
      if (isProtectedRel(resolvedRel)) { reject(norm, `protected-prefix: resolves to ${resolvedRel} — volatile state / generated bulk / internal surface is a bad ANSWER (mutation-lock is not a read ban; excluded as benchmark material)`); continue; }
      const volatileHit = VOLATILE_GENERATED.find((v) => v.match(resolvedRel));
      if (volatileHit) { reject(norm, `volatile-generated: ${volatileHit.why} — the correct answer changes without anyone navigating (distinct rail from protected-prefix)`); continue; }
      if (SECRET_NAME_RE.test(resolvedRel)) { reject(norm, `secret-shaped: resolves to ${resolvedRel} — credential-pattern paths are never valid answers`); continue; }
      const base = path.basename(norm);
      const ftsReachable = ftsPaths.has(norm);
      const basenameUnique = basenameCount.get(base) === 1;
      if (!ftsReachable) labeledUnreachable++;
      if (!basenameUnique) labeledNonUnique++;
      // LABELS, NOT FILTERS — blind spots stay askable (see header ruling).
      candidates.push({ path: norm, kind: path.extname(norm).replace(/^\./, '') || 'no-ext', fts_reachable: ftsReachable, basename_unique: basenameUnique });
    }
    candidates.sort((a, b) => a.path.localeCompare(b.path));
    // Even spread across the sorted list, not a head-slice: every k-th element,
    // fully reproducible, no alphabetical skew.
    const picked = [];
    if (candidates.length <= perArea) {
      picked.push(...candidates);
    } else {
      const step = candidates.length / perArea;
      for (let i = 0; i < perArea; i++) picked.push(candidates[Math.floor(i * step)]);
    }
    perAreaStats.push({ area: area.id, members: area.members, eligible: candidates.length, picked: picked.length });
    for (const c of picked) pool.push({ ...c, area: area.id });
  }

  // Deterministic pool hash for Atlas's composition lock: over the deterministic payload ONLY
  // (pool + sorted rejection manifest + exclusion counts), never the generated timestamp — an
  // identical corpus rebuild must produce an identical hash.
  const rejectedSorted = [...rejected].sort((a, b) => a.path.localeCompare(b.path));
  const hashPayload = JSON.stringify({ pool, rejected: rejectedSorted, excludedExisting });
  const poolHash = createHash('sha256').update(hashPayload).digest('hex');

  return {
    generated: new Date().toISOString(),
    poolHash,
    provenance_guard: 'paths + areas + kinds + labels only; no serves/does text, no tag content, no descriptions',
    perArea,
    totalCandidates: pool.length,
    areasWithCandidates: perAreaStats.filter((s) => s.picked > 0).length,
    exclusions: { existingAnswer: excludedExisting, protectedTotal: rejected.length - excludedExisting },
    labels: { fts_unreachable: labeledUnreachable, basename_non_unique: labeledNonUnique },
    rejected: rejectedSorted,
    areas: perAreaStats,
    pool,
  };
}

export function main(argv = process.argv.slice(2)) {
  const perArg = argv.find((a) => a.startsWith('--per-area='));
  const perArea = perArg ? parseInt(perArg.slice('--per-area='.length), 10) || 2 : 2;
  return buildPool({ perArea }).then((result) => {
    if (!existsSync(INDEX_DB)) throw new Error(`search index missing: ${INDEX_DB}`);
    writeFileSync(OUT_PATH, JSON.stringify(result, null, 2), 'utf8');
    // Separate deterministic rejection manifest (Hermes 2026-07-28: a filter with no rejection
    // log is indistinguishable from a filter that did nothing — and the log must outlive the
    // pool file it explains).
    writeFileSync(REJECTED_PATH, JSON.stringify({ poolHash: result.poolHash, rejected: result.rejected }, null, 2), 'utf8');
    if (argv.includes('--json')) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log(`bench-pool: ${result.totalCandidates} candidates across ${result.areasWithCandidates} areas (per-area=${perArea})`);
      console.log(`  wrote ${OUT_PATH}`);
      const dry = result.areas.filter((s) => s.picked === 0);
      if (dry.length) console.log(`  areas with ZERO eligible candidates: ${dry.length} (e.g. ${dry.slice(0, 3).map((d) => d.area).join(', ')})`);
      console.log(`  excluded (hard filters): existingAnswer=${result.exclusions.existingAnswer} protected/secret/symlink=${result.exclusions.protectedTotal} (manifest: _SYSTEM/state/atlas/bench-pool-rejected.json)`);
      const reasons = new Map();
      for (const r of result.rejected) { const k = r.reason.split(':')[0]; reasons.set(k, (reasons.get(k) || 0) + 1); }
      console.log(`  rejection reasons: ${[...reasons.entries()].map(([k, v]) => `${k}=${v}`).join(' ')}`);
      console.log(`  poolHash (deterministic payload): ${result.poolHash}`);
      console.log(`  labeled (kept, askable): fts_unreachable=${result.labels.fts_unreachable} basename_non_unique=${result.labels.basename_non_unique}`);
      console.log('  provenance guard: pool carries paths/areas/kinds/labels only — no serves/does, no tags, no descriptions');
    }
    return 0;
  }).catch((err) => {
    console.error(`bench-pool: ${err.message}`);
    return 1;
  });
}

const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMain) main().then((code) => { process.exitCode = code; });
