/**
 * EnergySurfaceScene.tsx
 *
 * 3D ΔU heightfield rendered from the REAL computeU 64×44 energy grid.
 * Data source: demos/data/energy-grid.js → _SYSTEM/src/data/energyGrid.ts
 * (generated by demos/build/gen-energy-grid.mjs from yuri-energy.mjs)
 *
 * Props:
 *   deltaU   — current ΔU value; a marker sphere highlights the closest grid cell
 *   animated — whether useFrame rotates the scene (default true)
 */

import React, { useRef, useMemo, useEffect } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import * as THREE from 'three';
import ENERGY_GRID from '../data/energyGrid';

// ── Types ─────────────────────────────────────────────────────────────────────

interface EnergySurfaceSceneProps {
  deltaU?: number;
  animated?: boolean;
}

// ── Colour map (inferno-ish, matches the standalone demo) ────────────────────

const CMAP: [number, [number, number, number]][] = [
  [0,    [2,   2,   12]],
  [0.25, [70,  16,  95]],
  [0.5,  [176, 52,  82]],
  [0.75, [249, 142, 9]],
  [1,    [252, 255, 190]],
];

function cmap(t: number): [number, number, number] {
  t = Math.min(1, Math.max(0, t));
  for (let i = 0; i < CMAP.length - 1; i++) {
    const [a, ca] = CMAP[i];
    const [b, cb] = CMAP[i + 1];
    if (t >= a && t <= b) {
      const f = (t - a) / (b - a || 1);
      return [
        (ca[0] + (cb[0] - ca[0]) * f) / 255,
        (ca[1] + (cb[1] - ca[1]) * f) / 255,
        (ca[2] + (cb[2] - ca[2]) * f) / 255,
      ];
    }
  }
  const last = CMAP[CMAP.length - 1][1];
  return [last[0] / 255, last[1] / 255, last[2] / 255];
}

// ── Scene inner (runs inside <Canvas>) ───────────────────────────────────────

const HEIGHT_SCALE = 8;   // world-units for U range
const WX = 10;            // x extent
const WZ = 7;             // z extent

function EnergySurface({ deltaU, animated }: EnergySurfaceSceneProps) {
  const groupRef = useRef<THREE.Group>(null);
  const markerRef = useRef<THREE.Mesh>(null);

  const { positions, colors, indices, markerPos, nx, nz } = useMemo(() => {
    const { nx, nz, U, uMin, uMax } = ENERGY_GRID;
    const uRange = uMax - uMin || 1;

    const positions = new Float32Array(nx * nz * 3);
    const colors    = new Float32Array(nx * nz * 3);

    for (let j = 0; j < nz; j++) {
      for (let i = 0; i < nx; i++) {
        const idx = j * nx + i;
        const u   = U[j][i];
        const t   = (u - uMin) / uRange;
        const y   = t * HEIGHT_SCALE;

        positions[idx * 3]     = -WX / 2 + (i / (nx - 1)) * WX;
        positions[idx * 3 + 1] = y;
        positions[idx * 3 + 2] = -WZ / 2 + (j / (nz - 1)) * WZ;

        const [r, g, b] = cmap(t);
        colors[idx * 3]     = r;
        colors[idx * 3 + 1] = g;
        colors[idx * 3 + 2] = b;
      }
    }

    const indices: number[] = [];
    for (let j = 0; j < nz - 1; j++) {
      for (let i = 0; i < nx - 1; i++) {
        const a = j * nx + i, b = a + 1, c = a + nx, d = c + 1;
        indices.push(a, c, b, b, c, d);
      }
    }

    // Marker position: find the grid cell closest to the given deltaU value
    // The grid x-axis is drift (0..1), z-axis is evidence count (0..50).
    // deltaU maps to a height; we pin the marker to the midpoint of drift and
    // the evidence value that produces the closest U to deltaU.
    const targetU = typeof deltaU === 'number' ? deltaU : uMin;
    let bestIdx = 0, bestDist = Infinity;
    for (let idx = 0; idx < nx * nz; idx++) {
      const j = Math.floor(idx / nx);
      const i = idx % nx;
      const dist = Math.abs(U[j][i] - targetU);
      if (dist < bestDist) { bestDist = dist; bestIdx = idx; }
    }
    const bj = Math.floor(bestIdx / nx);
    const bi = bestIdx % nx;
    const markerY = ((ENERGY_GRID.U[bj][bi] - uMin) / uRange) * HEIGHT_SCALE;
    const markerPos: [number, number, number] = [
      -WX / 2 + (bi / (nx - 1)) * WX,
      markerY + 0.15,
      -WZ / 2 + (bj / (nz - 1)) * WZ,
    ];

    return { positions, colors, indices, markerPos, nx, nz };
  }, [deltaU]);

  // Update marker when deltaU changes without rebuilding geometry
  useEffect(() => {
    if (!markerRef.current) return;
    markerRef.current.position.set(...markerPos);
  }, [markerPos]);

  useFrame((_, delta) => {
    if (!animated && animated !== undefined) return;
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.08;
    }
  });

  const geo = useMemo(() => {
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    g.setAttribute('color',    new THREE.BufferAttribute(colors, 3));
    g.setIndex(indices);
    g.computeVertexNormals();
    return g;
  }, [positions, colors, indices]);

  // Dispose geometry on unmount
  useEffect(() => () => { geo.dispose(); }, [geo]);

  return (
    <group ref={groupRef}>
      <ambientLight intensity={0.5} color={0x6a82c0} />
      <directionalLight position={[7, 14, 6]}  intensity={1.1} color={0xffffff} />
      <directionalLight position={[-8, 4, -7]} intensity={0.5} color={0xff8a4c} />

      <mesh geometry={geo}>
        <meshStandardMaterial
          vertexColors
          side={THREE.DoubleSide}
          roughness={0.45}
          metalness={0.12}
        />
      </mesh>

      {/* ΔU marker */}
      <mesh ref={markerRef} position={markerPos}>
        <sphereGeometry args={[0.1, 16, 12]} />
        <meshStandardMaterial
          color={0x36d1ff}
          emissive={0x36d1ff}
          emissiveIntensity={1.2}
          roughness={0.2}
        />
      </mesh>

      <gridHelper
        args={[Math.max(WX, WZ) * 1.4, 20, 0x1a2740, 0x121a2c]}
        position={[0, -0.05, 0]}
      />

      <OrbitControls enableDamping dampingFactor={0.08} makeDefault={false} />
    </group>
  );
}

// ── Public component ──────────────────────────────────────────────────────────

export default function EnergySurfaceScene(props: EnergySurfaceSceneProps): React.ReactElement {
  const { deltaU, animated = true } = props;

  return (
    <div style={{ width: '100%', height: '100%', minHeight: 300, background: '#05070d' }}>
      <Canvas
        camera={{ position: [9.6, 8.4, 12.8], fov: 45, near: 0.1, far: 500 }}
        gl={{ antialias: true, toneMapping: THREE.ACESFilmicToneMapping }}
        style={{ width: '100%', height: '100%' }}
      >
        <EnergySurface deltaU={deltaU} animated={animated} />
      </Canvas>
    </div>
  );
}
