export interface WorkItem {
  id: string;
  title: string;
  client: string;
  category: 'Commercial' | 'Music Video' | 'Documentary' | 'Corporate' | 'Event';
  year: number;
  thumbnail: string;
  hero: string;
  video: string;
  description: string;
  role: string;
  deliverables: string[];
  aspect: '4:3' | '16:9' | '1:1';
}

export const work: WorkItem[] = [
  {
    id: 'konzerthaus-winter-symphony',
    title: 'Winter Symphony',
    client: 'Wiener Konzerthaus',
    category: 'Event',
    year: 2025,
    thumbnail: '/images/work/konzerthaus-winter-symphony-thumb.jpg',
    hero: '/images/work/konzerthaus-winter-symphony-hero.jpg',
    video: 'https://vimeo.com/placeholder-01',
    description: 'A cinematic campaign film capturing the grandeur of the Konzerthaus winter season. Orchestral performances meet intimate backstage storytelling.',
    role: 'Director, DP, Post-Production',
    deliverables: ['60s TV Spot', 'Social Cut', 'Behind-the-Scenes Reel', 'Audio Mix'],
    aspect: '16:9',
  },
  {
    id: 'alpine-studios-ski-campaign',
    title: 'Peak Performance',
    client: 'Alpine Studios',
    category: 'Commercial',
    year: 2024,
    thumbnail: '/images/work/alpine-studios-ski-campaign-thumb.jpg',
    hero: '/images/work/alpine-studios-ski-campaign-hero.jpg',
    video: 'https://vimeo.com/placeholder-02',
    description: 'High-energy ski and winter sports gear campaign shot across three Austrian alpine resorts. Action-packed slow-motion and drone cinematography.',
    role: 'DP, Editor',
    deliverables: ['45s Brand Spot', 'Product Close-ups', 'Drone Montage', 'BTS Stills'],
    aspect: '16:9',
  },
  {
    id: 'vienna-heritage-documentary',
    title: 'Stones of the City',
    client: 'Vienna Heritage Co.',
    category: 'Documentary',
    year: 2025,
    thumbnail: '/images/work/vienna-heritage-documentary-thumb.jpg',
    hero: '/images/work/vienna-heritage-documentary-hero.jpg',
    video: 'https://vimeo.com/placeholder-03',
    description: 'A short documentary exploring Vienna’s architectural preservationists who restore centuries-old facades using traditional hand tools and methods.',
    role: 'Director, Cinematographer',
    deliverables: ['12-Minute Feature', 'Teaser Trailer', 'Interview Soundbites', 'Archival Stills'],
    aspect: '16:9',
  },
  {
    id: 'donauturm-loft-launch',
    title: 'Above the City',
    client: 'Donauturm Tourism',
    category: 'Commercial',
    year: 2026,
    thumbnail: '/images/work/donauturm-loft-launch-thumb.jpg',
    hero: '/images/work/donauturm-loft-launch-hero.jpg',
    video: 'https://vimeo.com/placeholder-04',
    description: 'Luxury sky-loft event launch atop the Donauturm. Sweeping panoramic views paired with elegant interior detail shots and guest interviews.',
    role: 'Director, Post-Production',
    deliverables: ['90s Launch Film', 'Instagram Reels', '360° Rooftop Tour', 'Photography Package'],
    aspect: '16:9',
  },
  {
    id: 'modul-university-brand',
    title: 'Future Leaders',
    client: 'Modul University',
    category: 'Corporate',
    year: 2024,
    thumbnail: '/images/work/modul-university-brand-thumb.jpg',
    hero: '/images/work/modul-university-brand-hero.jpg',
    video: 'https://vimeo.com/placeholder-05',
    description: 'Brand identity video for Modul University showcasing international student life, innovative campus facilities and academic excellence in Vienna.',
    role: 'Director, Editor',
    deliverables: ['3-Minute Brand Film', 'Student Testimonials', 'Campus Tour', 'Social Teasers'],
    aspect: '16:9',
  },
  {
    id: 'stadtkino-summer-nights',
    title: 'Sommerkino',
    client: 'Stadtkino',
    category: 'Event',
    year: 2023,
    thumbnail: '/images/work/stadtkino-summer-nights-thumb.jpg',
    hero: '/images/work/stadtkino-summer-nights-hero.jpg',
    video: 'https://vimeo.com/placeholder-06',
    description: 'Atmospheric event recap of Stadtkino’s outdoor summer film series. Golden-hour crowd shots, projection close-ups and Viennese summer vibes.',
    role: 'DP, Colorist',
    deliverables: ['90s Recap', '30s Teaser', 'Photo Gallery', 'Vertical Cut'],
    aspect: '16:9',
  },
  {
    id: 'volksoper-don-giovanni',
    title: 'Don Giovanni Reimagined',
    client: 'Volksoper',
    category: 'Music Video',
    year: 2025,
    thumbnail: '/images/work/volksoper-don-giovanni-thumb.jpg',
    hero: '/images/work/volksoper-don-giovanni-hero.jpg',
    video: 'https://vimeo.com/placeholder-07',
    description: 'A modern reinterpretation of Mozart’s Don Giovanni shot on stage at the Volksoper. Dramatic lighting and tight choreography drive the visual narrative.',
    role: 'Director, DP, Editor',
    deliverables: ['Full Music Video', 'Behind-the-Scenes', 'Stage Lighting Doc', 'Press Kit'],
    aspect: '16:9',
  },
  {
    id: 'belvedere-cafe-project',
    title: 'Café Belvedere',
    client: 'Belvedere Café',
    category: 'Commercial',
    year: 2024,
    thumbnail: '/images/work/belvedere-cafe-project-thumb.jpg',
    hero: '/images/work/belvedere-cafe-project-hero.jpg',
    video: 'https://vimeo.com/placeholder-08',
    description: 'Warm, pastry-focused brand film for the historic Belvedere Café. Slow pours, crumb close-ups and the quiet elegance of a Viennese coffee house.',
    role: 'Director, Food Stylist, Editor',
    deliverables: ['60s Brand Film', 'Menu Photography', 'Ambient Loop', 'Social Set'],
    aspect: '1:1',
  },
  {
    id: 'wiener-linien-safety',
    title: 'Ride Safe',
    client: 'Wiener Linien',
    category: 'Corporate',
    year: 2026,
    thumbnail: '/images/work/wiener-linien-safety-thumb.jpg',
    hero: '/images/work/wiener-linien-safety-hero.jpg',
    video: 'https://vimeo.com/placeholder-09',
    description: 'Safety campaign for Vienna’s public transport network combining clear instructional graphics with real employee testimonials and station verité.',
    role: 'Director, Writer, Post-Production',
    deliverables: ['2-Minute Safety Film', '4 x 30s Modules', 'Animated Infographics', 'Staff Training Cut'],
    aspect: '16:9',
  },
];
