/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function fnv1A(s: string): number
export interface HashParams {
  a: Array<number>
  b: Array<number>
}
export declare function makeHashes(k: number, seed: number): HashParams
export declare function minhashSignature(tokens: Array<string>, a: Array<number>, b: Array<number>): Array<number>
export declare function estimateJaccard(a: Array<number>, b: Array<number>): number
export declare function lshBands(sig: Array<number>, b: number, r: number): Array<string>
export interface BandTuning {
  b: number
  r: number
  crossover: number
  err: number
}
export declare function tuneBands(k: number, t: number): BandTuning
export declare function tokenize(text: string): Array<string>
/** jaccard of two texts (tokenize both, then set-similarity) — convenience for conformance. */
export declare function jaccardText(a: string, b: string): number
export declare function fib(n: number): number
export declare function phiSequence(count: number, x0: number): Array<number>
export declare function goldenAnglePoint(n: number): number
/** Minimize (x - target)^2 on [lo,hi] via golden-section — proves the closure-based search over FFI. */
export declare function goldenSectionMinQuadratic(target: number, lo: number, hi: number): number
export interface MatchResult {
  ids: Array<string>
  total: number
}
export declare function corpusMatchExact(ids: Array<string>, texts: Array<string>, query: string, threshold: number): MatchResult
export declare function corpusMatchPrefix(ids: Array<string>, texts: Array<string>, query: string, threshold: number): MatchResult
