#!/usr/bin/env pwsh
# @capability: yuri-desktop-app-builder-windows
# @serves: package yuri for windows | windows launcher for yuri | yuri.cmd | desktop shortcut windows
# @does: Windows analog of make-app.sh, phase-1. Zero third-party deps: only stock Windows tooling
#        (cmd.exe .cmd launcher + the WScript.Shell COM object for shortcut creation, both present on
#        every Windows install — no Chocolatey/winget/NuGet/Tauri/Electron). Generates, into an output
#        directory: yuri.cmd (runs `node <repo>\_SYSTEM\runtime\yuri-repl.mjs --start-brain` with the
#        repo root resolved relative to this script's OWN deployed location, mirroring make-app.sh's
#        REPO_ROOT-baked-in-at-build-time approach) plus a Desktop and/or Start Menu .lnk shortcut
#        pointing at yuri.cmd, using yuri.ico as the shortcut icon when present.
#        Mirrors make-app.sh's shape 1:1 (same entrypoint, same --start-brain flag, same
#        icon-optional/no-fail-without-it philosophy) so the two platforms stay in lockstep.
# @use: pwsh _SYSTEM/desktop/make-app-windows.ps1 [-OutDir <path>] [-Name <string>]
#              [-CreateDesktopShortcut] [-CreateStartMenuShortcut]
#       Authored and reviewed on macOS (no pwsh available on this dev machine — see README.md
#       residual-risk note); LIVE VALIDATION happens on the Windows box (i7-14700K/32GB/RTX 5060 Ti,
#       the "Jeffrey" machine) before this is trusted as verified-working, not just reviewed.
# @exports: (builder script; no importable functions — pure PowerShell CLI)

[CmdletBinding()]
param(
    [string]$OutDir = (Join-Path $PSScriptRoot ".output-windows"),
    [string]$Name = "Yuri",
    [switch]$CreateDesktopShortcut,
    [switch]$CreateStartMenuShortcut
)

$ErrorActionPreference = "Stop"

# ---- resolve repo root from THIS SCRIPT's location (mirrors make-app.sh's SCRIPT_DIR->REPO_ROOT) ----
# This script lives at <repo>\_SYSTEM\desktop\make-app-windows.ps1, so repo root is two levels up.
$ScriptDir = $PSScriptRoot
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path

$ReplEntry = Join-Path $RepoRoot "_SYSTEM\runtime\yuri-repl.mjs"
if (-not (Test-Path $ReplEntry)) {
    # $ErrorActionPreference = "Stop" makes Write-Error throw a terminating error here already;
    # no separate `exit 1` needed (that line would be dead code — Write-Error stops first).
    Write-Error "expected entrypoint missing: $ReplEntry (repo root resolved to: $RepoRoot — is this script still under _SYSTEM\desktop\?)"
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Warning "node not found on PATH. yuri.cmd will still be generated, but it needs Node.js installed to actually run. Install Node (nodejs.org or winget) on this machine before launching."
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# ---- icon (optional, additive — same philosophy as make-app.sh) ----
$IcoSource = Join-Path $ScriptDir "assets\generated\yuri.ico"
$IcoDest = $null
if (Test-Path $IcoSource) {
    $IcoDest = Join-Path $OutDir "$Name.ico"
    Copy-Item -Path $IcoSource -Destination $IcoDest -Force
    Write-Host "-> embedded icon: $IcoDest"
} else {
    Write-Host "-> note: no icon found at $IcoSource — building without one (run make-icon.sh on macOS/Linux first, or generate yuri.ico separately)"
}

# ---- yuri.cmd launcher ----
# Uses %~dp0 (the .cmd's OWN directory at run time, trailing backslash) so the launcher stays
# portable if the output dir is copied/moved on the Jeffrey box, exactly like make-app.sh's
# REPO_ROOT-baked-in-at-generation-time approach — except here we bake in the ABSOLUTE repo root at
# generation time (this script runs once, on this dev machine, to produce a deployable artifact; the
# repo path itself does not move once cloned onto the target Windows box, so an absolute path is the
# documented, simplest-correct choice for phase 1 — see README.md Windows phase-1 notes).
$CmdPath = Join-Path $OutDir "yuri.cmd"
$RepoRootWindowsStyle = $RepoRoot -replace '/', '\'
$ReplEntryWindowsStyle = $ReplEntry -replace '/', '\'

$CmdContent = @"
@echo off
setlocal
rem Yuri launcher (Windows phase-1) — runs the Yuri REPL from the repo root.
rem Generated by _SYSTEM\desktop\make-app-windows.ps1 — regenerate with that script if the repo moves.

set "YURI_REPO_ROOT=$RepoRootWindowsStyle"
set "YURI_ENTRY=$ReplEntryWindowsStyle"

if not exist "%YURI_ENTRY%" (
    echo Yuri: runtime entrypoint not found at %YURI_ENTRY%
    echo Keep this launcher pointed at the YURI-OS-MUSUBI repo, or regenerate it with
    echo _SYSTEM\desktop\make-app-windows.ps1
    pause
    exit /b 1
)

where node >nul 2>nul
if errorlevel 1 (
    echo Yuri needs Node.js on PATH. Install Node and relaunch.
    pause
    exit /b 1
)

cd /d "%YURI_REPO_ROOT%"
node "%YURI_ENTRY%" --start-brain
endlocal
"@

# Write as UTF-8 without BOM (a BOM before @echo off breaks cmd.exe parsing).
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($CmdPath, $CmdContent, $Utf8NoBom)
Write-Host "-> wrote $CmdPath"

# ---- shortcut creation via WScript.Shell COM (zero-dep, ships with every Windows install) ----
function New-YuriShortcut {
    param(
        [Parameter(Mandatory)][string]$ShortcutPath,
        [Parameter(Mandatory)][string]$TargetPath,
        [string]$IconPath
    )
    $WshShell = New-Object -ComObject WScript.Shell
    $Shortcut = $WshShell.CreateShortcut($ShortcutPath)
    $Shortcut.TargetPath = $TargetPath
    $Shortcut.WorkingDirectory = Split-Path -Parent $TargetPath
    $Shortcut.Description = "Yuri — desktop launcher (phase 1)"
    if ($IconPath -and (Test-Path $IconPath)) {
        # Explicit ",0" index is the defensive form of IconLocation — bare paths generally work for
        # .ico files (Explorer defaults to index 0), but some shell versions want it explicit.
        $Shortcut.IconLocation = "$IconPath,0"
    }
    $Shortcut.Save()
    Write-Host "-> wrote shortcut: $ShortcutPath"
}

if ($CreateDesktopShortcut) {
    $DesktopDir = [Environment]::GetFolderPath("Desktop")
    $ShortcutPath = Join-Path $DesktopDir "$Name.lnk"
    New-YuriShortcut -ShortcutPath $ShortcutPath -TargetPath $CmdPath -IconPath $IcoDest
}

if ($CreateStartMenuShortcut) {
    $StartMenuDir = [Environment]::GetFolderPath("StartMenu")
    $ProgramsDir = Join-Path $StartMenuDir "Programs"
    New-Item -ItemType Directory -Force -Path $ProgramsDir | Out-Null
    $ShortcutPath = Join-Path $ProgramsDir "$Name.lnk"
    New-YuriShortcut -ShortcutPath $ShortcutPath -TargetPath $CmdPath -IconPath $IcoDest
}

Write-Host "-> done. Launcher: $CmdPath"
if (-not $CreateDesktopShortcut -and -not $CreateStartMenuShortcut) {
    Write-Host "   (no shortcuts requested — pass -CreateDesktopShortcut and/or -CreateStartMenuShortcut to add one)"
}
Write-Host "   This script did not launch Yuri. Run yuri.cmd yourself, or double-click the shortcut, when ready."
