// ⬡ YURI_TRADING :: scoring engine — ESM, zero deps
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const logScale=(v,min,max,pts)=>{if(v<=min)return 0;if(v>=max)return pts;return clamp((Math.log(v)-Math.log(min))/(Math.log(max)-Math.log(min))*pts,0,pts)};
function decay(elapsed,halfLife,minWeight){if(elapsed<=0)return 1;return Math.max(minWeight,Math.exp(-Math.LN2/halfLife*elapsed))}
function normalizeScore(raw,max){return clamp(Math.round((raw/max)*100),0,100)}
const SYMBOL_MAP={WBTC:'BTC',WETH:'ETH',STETH:'ETH',RETH:'ETH'};
function canonicalizeToken(s){const u=(s||'???').toUpperCase().trim();return SYMBOL_MAP[u]||u}

function scoreDexPair(p){const vs=clamp(logScale(p.volumeSpikePct,200,3000,15),0,15);const ls=clamp(logScale(p.liquidity,1e4,1e6,10),0,10);const as=clamp(10*(1-(p.age/3600)/24),0,10);return{token:canonicalizeToken(p.baseToken||'???'),score:vs+ls+as,signals:[]}}
function scoreFunding(a){const abs=Math.abs(a.fundingRate||0);const rs=clamp(logScale(abs,0.0001,0.003,20),0,20);const sig=[];if(rs>=10)sig.push('HIGH_FUNDING');const bias=(a.fundingRate||0)>0.001?'SHORT_BIAS':(a.fundingRate||0)<-0.001?'LONG_BIAS':'NEUTRAL';if(bias!=='NEUTRAL')sig.push(bias);const os=clamp(logScale(a.openInterest||0,1e6,1e8,10),0,10);return{token:canonicalizeToken(a.asset||'???'),score:rs+os,bias,signals:sig}}
function scoreWhale(tx){const as=clamp(logScale(tx.amountUsd||0,5e5,5e7,15),0,15);const sig=[];if(as>=12)sig.push('MEGA_WHALE');const ac=tx.type==='EXCHANGE_WITHDRAWAL'?10:tx.type==='EXCHANGE_DEPOSIT'?2:0;if(ac===10)sig.push('ACCUMULATION');return{token:canonicalizeToken(tx.symbol||'???'),score:as+ac,signals:sig}}

function scoreNewsImpact(articles,token){const rel=articles.filter(a=>(a.assets||[]).includes(token));if(!rel.length)return{score:0,evidence:[]};let s=0;const ev=[];for(const a of rel){s+=(a.sentiment==='BULLISH'?3:a.sentiment==='BEARISH'?-3:0)*(a.strength||1);ev.push(`[${a.sentiment}] ${(a.headline||'').slice(0,60)}`)}return{score:clamp(s,-15,15),evidence:ev.slice(0,5)}}

function scoreSentiment(fng){if(!fng.length)return{score:0,evidence:[]};const v=fng[0].value||50;const c=v<=25?8:v>=75?-6:0;return{score:c,evidence:[`Fear & Greed: ${fng[0].sentiment} (${v}/100) ${fng[0].emoji}`]}}

function mergeSignals(dp,fa,wt){const m=new Map();for(const d of dp){if(!m.has(d.token))m.set(d.token,{dx:[],fu:[],wh:[]});m.get(d.token).dx.push(d)}for(const f of fa){if(!m.has(f.token))m.set(f.token,{dx:[],fu:[],wh:[]});m.get(f.token).fu.push(f)}for(const w of wt){if(!m.has(w.token))m.set(w.token,{dx:[],fu:[],wh:[]});m.get(w.token).wh.push(w)}const out=[];for(const[token,f]of m){const src=[];if(f.dx.length)src.push('dex');if(f.fu.length)src.push('funding');if(f.wh.length)src.push('whale');const best=Math.max(f.dx.reduce((mx,s)=>s.score>mx?s.score:mx,0),f.fu.reduce((mx,s)=>s.score>mx?s.score:mx,0),f.wh.reduce((mx,s)=>s.score>mx?s.score:mx,0));const bonus=src.length>=2?10:0;const agg=Math.round(best+bonus);const allSigs=[...new Set([...f.dx,...f.fu,...f.wh].flatMap(s=>s.signals))];const urg=agg>=65?'CRITICAL':agg>=45?'ELEVATED':agg>=20?'WATCH':'NEUTRAL';out.push({token,sources:src,sourceCount:src.length,aggregateScore:agg,urgency:urg,topSignals:allSigs.slice(0,8),evidence:[]})}out.sort((a,b)=>b.aggregateScore-a.aggregateScore);return out}

export function computeSignals(feeds){const now=Date.now();const dp=(feeds.dex?.pairs||[]).map(p=>{const s=scoreDexPair(p);const d=decay(p.age||0,21600,0.15);s.score=normalizeScore(Math.round(s.score*d),35);return s});const fa=(feeds.funding?.assets||[]).map(a=>{const s=scoreFunding(a);s.score=normalizeScore(s.score,30);return s});const wt=(feeds.whale?.transactions||[]).map(tx=>{const s=scoreWhale(tx);const el=tx.timestamp?(now-new Date(tx.timestamp).getTime())/1000:0;const d=decay(el,3600,0.2);s.score=normalizeScore(Math.round(s.score*d),25);return s});const merged=mergeSignals(dp,fa,wt);const articles=feeds.news?.articles||[];const fng=feeds.feargreed?.data||[];const fngScore=scoreSentiment(fng);for(const m of merged){const ns=scoreNewsImpact(articles,m.token);if(ns.score!==0){m.aggregateScore=clamp(m.aggregateScore+ns.score,0,100);m.evidence.push(...ns.evidence);if(!m.sources.includes('news')){m.sources.push('news');m.sourceCount=m.sources.length}}if(fngScore.score!==0){m.aggregateScore=clamp(m.aggregateScore+fngScore.score,0,100);m.evidence.push(...fngScore.evidence)}m.urgency=m.aggregateScore>=65?'CRITICAL':m.aggregateScore>=45?'ELEVATED':m.aggregateScore>=20?'WATCH':'NEUTRAL';m.maxConfidence=m.sourceCount>=2?'HIGH':m.aggregateScore>=50?'MEDIUM':'LOW'}merged.sort((a,b)=>b.aggregateScore-a.aggregateScore);return{ts:new Date().toISOString(),summary:{totalDexSignals:dp.length,totalFundingSignals:fa.length,totalWhaleSignals:wt.length,mergedTokens:merged.length,criticalCount:merged.filter(m=>m.urgency==='CRITICAL').length,elevatedCount:merged.filter(m=>m.urgency==='ELEVATED').length},topMerged:merged.slice(0,20)}}
