/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function fnv1A(s: string): number
export interface HashParams {
  a: Array<number>
  b: Array<number>
}
export declare function makeHashes(k: number, seed: number): HashParams
export declare function minhashSignature(tokens: Array<string>, a: Array<number>, b: Array<number>): Array<number>
export declare function estimateJaccard(a: Array<number>, b: Array<number>): number
export declare function lshBands(sig: Array<number>, b: number, r: number): Array<string>
export interface BandTuning {
  b: number
  r: number
  crossover: number
  err: number
}
export declare function tuneBands(k: number, t: number): BandTuning
export declare function tokenize(text: string): Array<string>
export declare function jaccardText(a: string, b: string): number
export declare function fib(n: number): number
export declare function phiSequence(count: number, x0: number): Array<number>
export declare function goldenAnglePoint(n: number): number
export declare function goldenSectionMinQuadratic(target: number, lo: number, hi: number): number
export interface MatchResult {
  ids: Array<string>
  total: number
}
export declare function corpusMatchExact(ids: Array<string>, texts: Array<string>, query: string, threshold: number): MatchResult
export declare function corpusMatchPrefix(ids: Array<string>, texts: Array<string>, query: string, threshold: number): MatchResult
export declare function statsRankWithTies(values: Array<number>): Array<number>
export declare function statsMedian(values: Array<number>): number
export declare function statsPercentile(values: Array<number>, p: number): number
export declare function statsWeightedVariance(values: Array<number>, weights: Array<number>): number
export declare function distribNormalize(values: Array<number>): Array<number>
export declare function distribPNorm(values: Array<number>, p: number): number
export declare function distribWeightedStdDev(values: Array<number>, weights: Array<number>): number
export declare function distribCosineSimilarity(left: Array<number>, right: Array<number>): number
export declare function distribPearson(xs: Array<number>, ys: Array<number>): number
export declare function distribSpearman(xs: Array<number>, ys: Array<number>): number
