<script lang="ts">
  import { onMount } from "svelte";
  import { supabase, hasClient } from "$lib/db";

  interface Prediction {
    client_code: string;
    likely_ask: string;
    precomputed: string;
    confidence?: number;
  }

  interface Props {
    limit?: number;  // how many to surface in the strip
    showTitle?: boolean;
  }
  let { limit = 3, showTitle = true }: Props = $props();

  let predictions = $state<Prediction[]>([]);
  let generatedAt = $state<string | null>(null);
  let loading = $state(true);

  onMount(async () => {
    if (!hasClient()) { loading = false; return; }
    try {
      const { data, error } = await supabase()
        .from("audit_log")
        .select("details, created_at")
        .eq("action", "cto.predictions.v1")
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      if (error || !data) { loading = false; return; }
      const raw = (data.details?.predictions || []) as Prediction[];
      predictions = raw;
      generatedAt = data.details?.generated_at || data.created_at;
    } catch (err) {
      console.warn("[PredictionStrip]", err);
    } finally {
      loading = false;
    }
  });

  const top = $derived(predictions.slice(0, limit));

  function fmtTimeAgo(iso?: string | null): string {
    if (!iso) return "";
    const diffMs = Date.now() - new Date(iso).getTime();
    const h = Math.floor(diffMs / 3_600_000);
    if (h < 1) return "minutes ago";
    if (h < 24) return `${h}h ago`;
    return `${Math.floor(h / 24)}d ago`;
  }
</script>

{#if !loading && top.length > 0}
  <section class="pred-strip glass glass--thick">
    {#if showTitle}
      <header class="pred-head">
        <div class="stack gap-0">
          <span class="pred-label">EXEO · AI NEXT-ASKS</span>
          <span class="pred-sub">Generated by CTO overnight pass · {fmtTimeAgo(generatedAt)}</span>
        </div>
        <a class="pred-more" href="/intel#predictions">See all {predictions.length} →</a>
      </header>
    {/if}
    <div class="pred-row">
      {#each top as p, i}
        <a class="pred-card" href={`/clients?open=${p.client_code}`} title={p.precomputed} style={`--i: ${i}`}>
          <header class="pred-card-head">
            <span class="pred-code font-mono">{p.client_code}</span>
            <span class="pred-conf">{p.confidence ? (Math.round(p.confidence * 100) + "%") : "likely"}</span>
          </header>
          <p class="pred-ask">{p.likely_ask}</p>
          <p class="pred-answer">{p.precomputed}</p>
        </a>
      {/each}
    </div>
  </section>
{/if}

<style>
  .pred-strip {
    padding: 20px 22px;
    border-radius: var(--r-lg);
    border: 1px solid rgba(34,211,238,0.22);
    box-shadow: 0 0 0 1px rgba(34,211,238,0.08), 0 10px 36px rgba(34,211,238,0.08);
    background: linear-gradient(135deg, rgba(34,211,238,0.04), rgba(168,85,247,0.04));
    position: relative;
    overflow: hidden;
  }
  .pred-strip::before {
    content: ""; position: absolute; top: 0; left: 0; bottom: 0;
    width: 3px;
    background: linear-gradient(180deg, var(--a) 0%, var(--a2) 100%);
    box-shadow: 0 0 12px var(--a);
  }
  .pred-head {
    display: flex; justify-content: space-between; align-items: flex-end;
    margin-bottom: 14px;
    flex-wrap: wrap; gap: 10px;
  }
  .pred-label {
    font-family: "Space Grotesk", sans-serif;
    font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase;
    color: var(--a); font-weight: 600;
  }
  .pred-sub { font-size: 10.5px; color: var(--t3); letter-spacing: 0.03em; }
  .pred-more {
    font-size: 12px;
    color: var(--a);
    text-decoration: none;
    font-family: "Space Grotesk", sans-serif;
  }
  .pred-more:hover { text-decoration: underline; }

  .pred-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 12px;
  }
  .pred-card {
    display: flex; flex-direction: column; gap: 8px;
    padding: 14px 16px;
    background: var(--s1);
    border: 1px solid var(--b1);
    border-radius: var(--r-md);
    text-decoration: none;
    color: inherit;
    transition: background var(--dur-fast), border-color var(--dur-fast), transform var(--dur-fast);
    animation: pred-in 420ms var(--ease-spring) both;
    animation-delay: calc(var(--i, 0) * 80ms);
  }
  .pred-card:hover {
    background: var(--s2);
    border-color: color-mix(in oklab, var(--a) 40%, var(--b1));
    transform: translateY(-2px);
  }
  .pred-card-head {
    display: flex; justify-content: space-between; align-items: center;
  }
  .pred-code {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    background: color-mix(in oklab, var(--a) 16%, transparent);
    color: var(--tx);
    letter-spacing: 0.06em;
  }
  .pred-conf {
    font-size: 10px;
    color: var(--t3);
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }
  .pred-ask {
    margin: 0;
    font-size: 13px;
    color: var(--tx);
    font-weight: 500;
    line-height: 1.3;
  }
  .pred-answer {
    margin: 0;
    font-size: 11.5px;
    color: var(--t2);
    line-height: 1.4;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  @keyframes pred-in {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }
</style>
