//! nexus_core::corpus_match — deterministic Jaccard matcher with a COMPLETE prefix-filter index.
//! Rust port of the corpus-match.mjs kernel (Jaccard path). SQLite/FTS adapters, cosine, token
//! expansion + the CLI stay in Node. Ported by Codex R3 (2026-06-06), reconciled to the
//! jaccard::OrderedTokenSet type + verified by the completeness-invariant test (prefix == exact).
use std::collections::{HashMap, HashSet};

use crate::jaccard::{jaccard, tokenize, OrderedTokenSet};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CorpusItem<'a> {
    pub id: &'a str,
    pub text: &'a str,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Match {
    pub id: String,
    /// Jaccard score rounded to four decimals (JS Number(s.toFixed(4))).
    pub score: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ExactMatchResult {
    pub matches: Vec<Match>,
    pub total_above_threshold: usize,
    pub scanned: usize,
    pub mode: &'static str,
    pub threshold: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct PrefixFilterMatchResult {
    pub matches: Vec<Match>,
    pub total_above_threshold: usize,
    pub candidates: usize,
    pub scanned: usize,
    pub mode: &'static str,
    pub threshold: f64,
    pub complete: bool,
}

#[derive(Debug, Clone)]
pub struct Index {
    ids: Vec<String>,
    sets: Vec<OrderedTokenSet>,
    prefix_filter: Option<PrefixFilterIndex>,
    lsh_enabled: bool,
}

#[derive(Debug, Clone)]
struct PrefixFilterIndex {
    rank: HashMap<String, usize>,
    inverted: HashMap<String, Vec<usize>>,
    build_threshold: f64,
}

impl Index {
    #[must_use] pub fn len(&self) -> usize { self.ids.len() }
    #[must_use] pub fn is_empty(&self) -> bool { self.ids.is_empty() }
    #[must_use] pub fn lsh_enabled(&self) -> bool { self.lsh_enabled }
}

#[must_use]
pub fn build_index(items: &[CorpusItem<'_>], threshold: f64, prefix_filter: bool, lsh: bool) -> Index {
    let ids: Vec<String> = items.iter().map(|item| item.id.to_owned()).collect();
    let sets: Vec<OrderedTokenSet> = items.iter().map(|item| tokenize(item.text)).collect();
    build_index_from_sets(ids, sets, threshold, prefix_filter, lsh)
}

// ── featureFn serializable contract ──────────────────────────────────────────────────────────────
// JS `buildIndex`/`matchExact`/`matchPrefixFilter` each accept an `opts.featureFn` (default =
// `tokenize`) that maps text → a feature Set. All four hot callers (circuitry-auto-register,
// cross-reference, memory-match, yuri-match) pass a custom closure from yuri-token-expand that emits
// namespaced features (`tok:` / `c4:` / `sem:` …). A JS closure cannot cross the napi/wasm FFI
// boundary, so the serializable contract is: THE CALLER COMPUTES `featureFn(text)` ITSELF and passes
// the resulting STRING ARRAYS across. Rust treats every feature as an OPAQUE string and runs the
// exact-same Jaccard / prefix-filter / sort logic — so the ids-only output is bit-identical to the JS
// featureFn path (proven by the featureFn oracle vectors, generated by calling REAL JS buildIndex/
// matchExact/matchPrefixFilter with a custom featureFn).
//
// Contract detail (load-bearing): JS stores the featureFn `Set` directly and later spreads it with
// `[...set]`, which yields INSERTION order. So the caller must pass `[...featureFn(text)]`
// (insertion-ordered, de-duplicated by the JS Set). `features_to_set` rebuilds an `OrderedTokenSet`
// preserving first-seen order + de-dup, matching the JS Set semantics that jaccard and the
// prefix-filter depend on. With the default tokenizer this is exactly `build_index` (verified: the
// default-tokenize oracle and the featureFn oracle both pass against this one code path).

fn features_to_set(features: &[String]) -> OrderedTokenSet {
    let mut set = OrderedTokenSet::new();
    for feature in features { set.insert(feature.clone()); }
    set
}

/// Build an index from PRE-COMPUTED feature arrays (the featureFn serializable contract).
/// `ids` and `feature_sets` are index-aligned; each `feature_sets[i]` is `[...featureFn(text_i)]`
/// (insertion-ordered; the JS Set already de-duplicated, and `features_to_set` de-dups defensively).
#[must_use]
pub fn build_index_from_features(
    ids: &[String], feature_sets: &[Vec<String>], threshold: f64, prefix_filter: bool, lsh: bool,
) -> Index {
    let ids: Vec<String> = ids.to_vec();
    let sets: Vec<OrderedTokenSet> = feature_sets.iter().map(|f| features_to_set(f)).collect();
    build_index_from_sets(ids, sets, threshold, prefix_filter, lsh)
}

/// Exact match using PRE-COMPUTED query features (`[...featureFn(queryText)]`). ids-only conformance.
#[must_use]
pub fn match_exact_with_features(index: &Index, query_features: &[String], threshold: f64, top: usize) -> ExactMatchResult {
    match_exact_with_set(index, &features_to_set(query_features), threshold, top)
}

/// Prefix-filter match using PRE-COMPUTED query features (`[...featureFn(queryText)]`). ids-only.
#[must_use]
pub fn match_prefix_filter_with_features(index: &Index, query_features: &[String], threshold: f64, top: usize) -> PrefixFilterMatchResult {
    match_prefix_filter_with_set(index, &features_to_set(query_features), threshold, top)
}

fn build_index_from_sets(ids: Vec<String>, sets: Vec<OrderedTokenSet>, threshold: f64, prefix_filter: bool, lsh: bool) -> Index {
    let build_threshold = valid_threshold_or_default(threshold);
    let prefix_filter = if prefix_filter { Some(build_prefix_filter(&sets, build_threshold)) } else { None };
    Index { ids, sets, prefix_filter, lsh_enabled: lsh }
}

/// Complete O(N) Jaccard match (default tokenizer feature path).
#[must_use]
pub fn match_exact(index: &Index, query: &str, threshold: f64, top: usize) -> ExactMatchResult {
    match_exact_with_set(index, &tokenize(query), threshold, top)
}

fn match_exact_with_set(index: &Index, qset: &OrderedTokenSet, threshold: f64, top: usize) -> ExactMatchResult {
    let mut matches = Vec::new();
    for (idx, set) in index.sets.iter().enumerate() {
        let score = jaccard(qset, set);
        if score >= threshold {
            matches.push(Match { id: index.ids[idx].clone(), score: round4(score) });
        }
    }
    sort_matches(&mut matches);
    let total_above_threshold = matches.len();
    truncate_top(&mut matches, top);
    ExactMatchResult { matches, total_above_threshold, scanned: index.len(), mode: "exact", threshold }
}

/// Complete prefix-filter match for thresholds covered by the build threshold.
/// Invariant: the id-set MUST equal match_exact whenever threshold >= build_threshold.
#[must_use]
pub fn match_prefix_filter(index: &Index, query: &str, threshold: f64, top: usize) -> PrefixFilterMatchResult {
    match_prefix_filter_with_set(index, &tokenize(query), threshold, top)
}

fn match_prefix_filter_with_set(index: &Index, qset: &OrderedTokenSet, threshold: f64, top: usize) -> PrefixFilterMatchResult {
    let Some(prefix_filter) = &index.prefix_filter else {
        return PrefixFilterMatchResult {
            matches: Vec::new(), total_above_threshold: 0, candidates: 0,
            scanned: index.len(), mode: "prefix-filter", threshold, complete: false,
        };
    };

    let t = threshold.max(prefix_filter.build_threshold);
    let mut qsorted: Vec<String> = qset.tokens().to_vec();
    qsorted.sort_by(|a, b| rank_for(prefix_filter, a).cmp(&rank_for(prefix_filter, b)).then_with(|| a.cmp(b)));

    let qlen = qsorted.len();
    let qprefix_len = prefix_len_at(qlen, t);
    let lo_len = (t * qlen as f64).ceil() as usize;
    let hi_len = if t > 0.0 { (qlen as f64 / t).floor() as usize } else { usize::MAX };
    let mut candidates = HashSet::new();

    for token in qsorted.iter().take(qprefix_len.min(qlen)) {
        if let Some(indexes) = prefix_filter.inverted.get(token) {
            for idx in indexes {
                let len = index.sets[*idx].len();
                if len >= lo_len && len <= hi_len { candidates.insert(*idx); }
            }
        }
    }

    let mut matches = Vec::new();
    for idx in &candidates {
        let score = jaccard(qset, &index.sets[*idx]);
        if score >= threshold {
            matches.push(Match { id: index.ids[*idx].clone(), score: round4(score) });
        }
    }
    sort_matches(&mut matches);
    let total_above_threshold = matches.len();
    truncate_top(&mut matches, top);

    PrefixFilterMatchResult {
        matches, total_above_threshold, candidates: candidates.len(), scanned: index.len(),
        mode: "prefix-filter", threshold,
        complete: threshold > 0.0 && threshold >= prefix_filter.build_threshold,
    }
}

fn build_prefix_filter(sets: &[OrderedTokenSet], threshold: f64) -> PrefixFilterIndex {
    let mut df: HashMap<String, usize> = HashMap::new();
    for set in sets {
        for token in set.tokens() { *df.entry(token.clone()).or_insert(0) += 1; }
    }
    let mut tokens: Vec<String> = df.keys().cloned().collect();
    tokens.sort_by(|a, b| df[a].cmp(&df[b]).then_with(|| a.cmp(b)));
    let mut rank = HashMap::new();
    for (idx, token) in tokens.into_iter().enumerate() { rank.insert(token, idx); }

    let mut inverted: HashMap<String, Vec<usize>> = HashMap::new();
    for (idx, set) in sets.iter().enumerate() {
        let mut item_tokens: Vec<String> = set.tokens().to_vec();
        item_tokens.sort_by(|a, b| rank[a].cmp(&rank[b]).then_with(|| a.cmp(b)));
        let prefix_len = prefix_len_at(item_tokens.len(), threshold);
        for token in item_tokens.iter().take(prefix_len.min(item_tokens.len())) {
            inverted.entry(token.clone()).or_default().push(idx);
        }
    }
    PrefixFilterIndex { rank, inverted, build_threshold: threshold }
}

fn prefix_len_at(len: usize, threshold: f64) -> usize {
    let needed = (threshold * len as f64).ceil() as usize;
    len.saturating_sub(needed).saturating_add(1).max(1)
}

fn rank_for(prefix_filter: &PrefixFilterIndex, token: &str) -> usize {
    prefix_filter.rank.get(token).copied().unwrap_or(usize::MAX)
}

fn sort_matches(matches: &mut [Match]) {
    matches.sort_by(|a, b| b.score.total_cmp(&a.score).then_with(|| a.id.cmp(&b.id)));
}

fn truncate_top(matches: &mut Vec<Match>, top: usize) {
    if top > 0 && matches.len() > top { matches.truncate(top); }
}

fn round4(value: f64) -> f64 { (value * 10_000.0).round() / 10_000.0 }

fn valid_threshold_or_default(threshold: f64) -> f64 {
    if threshold.is_finite() && threshold > 0.0 && threshold <= 1.0 { threshold } else { 0.3 }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn corpus() -> Vec<CorpusItem<'static>> {
        vec![
            CorpusItem { id: "a", text: "session resume cortex decoder circuitry build plan next steps wire engine" },
            CorpusItem { id: "b", text: "session resume cortex decoder circuitry build plan next steps wire engine extra" },
            CorpusItem { id: "c", text: "cold call opener objection rebuttal social selling outreach sequence buyer persona" },
            CorpusItem { id: "d", text: "reflected xss login form input field cross site scripting" },
            CorpusItem { id: "e", text: "login form input validation prevents reflected xss in field" },
            CorpusItem { id: "f", text: "subdomain takeover dangling dns cname record cloud asset" },
        ]
    }

    #[test]
    fn prefix_filter_matches_exact_id_set_across_thresholds() {
        let items = corpus();
        let index = build_index(&items, 0.2, true, false);
        let queries = [
            "session resume cortex decoder engine wire plan",
            "reflected xss login input form",
            "subdomain dangling cname",
            "social selling cold call objection",
            "tokens absent from the corpus",
        ];
        let thresholds = [0.2, 0.25, 0.3, 0.45, 0.6, 0.8, 1.0];
        for query in queries {
            for threshold in thresholds {
                let exact = match_exact(&index, query, threshold, 0);
                let prefix = match_prefix_filter(&index, query, threshold, 0);
                let exact_ids: Vec<&str> = exact.matches.iter().map(|m| m.id.as_str()).collect();
                let prefix_ids: Vec<&str> = prefix.matches.iter().map(|m| m.id.as_str()).collect();
                assert!(prefix.complete, "query={query} threshold={threshold}");
                assert_eq!(prefix_ids, exact_ids, "query={query} threshold={threshold}");
                assert_eq!(prefix.total_above_threshold, exact.total_above_threshold, "query={query} threshold={threshold}");
            }
        }
    }

    #[test]
    fn top_truncates_matches_but_not_total() {
        let items = corpus();
        let index = build_index(&items, 0.2, true, false);
        let exact = match_exact(&index, "session resume cortex decoder engine wire plan", 0.2, 1);
        let prefix = match_prefix_filter(&index, "session resume cortex decoder engine wire plan", 0.2, 1);
        assert_eq!(exact.matches.len(), 1);
        assert_eq!(prefix.matches.len(), 1);
        assert!(exact.total_above_threshold > exact.matches.len());
        assert_eq!(prefix.total_above_threshold, exact.total_above_threshold);
    }

    #[test]
    fn score_sort_tie_breaks_by_id_ascending() {
        let items = vec![
            CorpusItem { id: "b", text: "alpha beta gamma" },
            CorpusItem { id: "a", text: "alpha beta gamma" },
        ];
        let index = build_index(&items, 0.2, true, false);
        let exact = match_exact(&index, "alpha beta gamma", 0.2, 0);
        assert_eq!(exact.matches[0].id, "a");
        assert_eq!(exact.matches[1].id, "b");
    }

    fn sorted_ids(matches: &[Match]) -> Vec<String> {
        let mut ids: Vec<String> = matches.iter().map(|m| m.id.clone()).collect();
        ids.sort();
        ids
    }

    // ── JS-ORACLE-PINNED VECTORS (default tokenize path) ──────────────────────────────────────────
    // Generated by CALLING THE REAL JS corpus-match.mjs in node (buildIndex/matchExact/
    // matchPrefixFilter, lsh:false, buildThreshold=0.2) over the same corpus() + queries.
    // Conformance is ids-only, order-insensitive setEq (per Phase-0: scores never cross FFI).
    // Each tuple: (query_index, threshold, expected_ids_sorted, expected_total).
    #[test]
    fn default_tokenize_path_matches_js_oracle() {
        let items = corpus();
        let index = build_index(&items, 0.2, true, false);
        let queries = [
            "session resume cortex decoder engine wire plan",
            "reflected xss login input form",
            "subdomain dangling cname",
            "social selling cold call objection",
            "tokens absent from the corpus",
        ];
        // (qi, t, ids, total) — pinned from real-JS output.
        let oracle: &[(usize, f64, &[&str], usize)] = &[
            (0, 0.2, &["a", "b"], 2), (0, 0.25, &["a", "b"], 2), (0, 0.3, &["a", "b"], 2),
            (0, 0.45, &["a", "b"], 2), (0, 0.6, &["a"], 1), (0, 0.8, &[], 0), (0, 1.0, &[], 0),
            (1, 0.2, &["d", "e"], 2), (1, 0.25, &["d", "e"], 2), (1, 0.3, &["d", "e"], 2),
            (1, 0.45, &["d", "e"], 2), (1, 0.6, &["e"], 1), (1, 0.8, &[], 0), (1, 1.0, &[], 0),
            (2, 0.2, &["f"], 1), (2, 0.25, &["f"], 1), (2, 0.3, &["f"], 1),
            (2, 0.45, &[], 0), (2, 0.6, &[], 0), (2, 0.8, &[], 0), (2, 1.0, &[], 0),
            (3, 0.2, &["c"], 1), (3, 0.25, &["c"], 1), (3, 0.3, &["c"], 1), (3, 0.45, &["c"], 1),
            (3, 0.6, &[], 0), (3, 0.8, &[], 0), (3, 1.0, &[], 0),
            (4, 0.2, &[], 0), (4, 0.25, &[], 0), (4, 0.3, &[], 0), (4, 0.45, &[], 0),
            (4, 0.6, &[], 0), (4, 0.8, &[], 0), (4, 1.0, &[], 0),
        ];
        for &(qi, t, ids, total) in oracle {
            let want: Vec<String> = ids.iter().map(|s| (*s).to_string()).collect();
            let exact = match_exact(&index, queries[qi], t, 0);
            let prefix = match_prefix_filter(&index, queries[qi], t, 0);
            assert_eq!(sorted_ids(&exact.matches), want, "exact qi={qi} t={t}");
            assert_eq!(exact.total_above_threshold, total, "exact total qi={qi} t={t}");
            assert_eq!(sorted_ids(&prefix.matches), want, "prefix qi={qi} t={t}");
            assert_eq!(prefix.total_above_threshold, total, "prefix total qi={qi} t={t}");
            assert!(prefix.complete, "prefix complete qi={qi} t={t}");
        }
    }

    // ── JS-ORACLE-PINNED VECTORS (featureFn serializable-contract path) ───────────────────────────
    // The featureFn used in JS to generate this oracle: tokens + char-4 shingles, namespaced
    // `tok:`/`c4:` (mirrors the yuri-token-expand feature SHAPE — opaque namespaced strings). JS:
    //   featureFn(text) = { for tok in tokenize(text): add("tok:"+tok), add "c4:"+shingle(^tok$, 4) }
    // The pre-computed `[...featureFn(text)]` arrays below were captured from that JS run, then fed
    // IDENTICALLY into JS buildIndex/matchExact/matchPrefixFilter (featureFn passed) AND into the Rust
    // build_index_from_features / match_*_with_features here. ids-only setEq must match. This is the
    // contract that lets the JS-closure featureFn cross the FFI boundary as precomputed string arrays.
    fn feature_corpus() -> (Vec<String>, Vec<Vec<String>>) {
        let ids = ["a", "b", "c", "d", "e"].iter().map(|s| (*s).to_string()).collect();
        let raw: &[&[&str]] = &[
            &["tok:session","c4:^ses","c4:sess","c4:essi","c4:ssio","c4:sion","c4:ion$","tok:resume","c4:^res","c4:resu","c4:esum","c4:sume","c4:ume$","tok:cortex","c4:^cor","c4:cort","c4:orte","c4:rtex","c4:tex$","tok:decoder","c4:^dec","c4:deco","c4:ecod","c4:code","c4:oder","c4:der$","tok:build","c4:^bui","c4:buil","c4:uild","c4:ild$","tok:plan","c4:^pla","c4:plan","c4:lan$"],
            &["tok:session","c4:^ses","c4:sess","c4:essi","c4:ssio","c4:sion","c4:ion$","tok:resume","c4:^res","c4:resu","c4:esum","c4:sume","c4:ume$","tok:cortex","c4:^cor","c4:cort","c4:orte","c4:rtex","c4:tex$","tok:decoder","c4:^dec","c4:deco","c4:ecod","c4:code","c4:oder","c4:der$","tok:build","c4:^bui","c4:buil","c4:uild","c4:ild$","tok:plan","c4:^pla","c4:plan","c4:lan$","tok:extra","c4:^ext","c4:extr","c4:xtra","c4:tra$"],
            &["tok:cold","c4:^col","c4:cold","c4:old$","tok:call","c4:^cal","c4:call","c4:all$","tok:opener","c4:^ope","c4:open","c4:pene","c4:ener","c4:ner$","tok:objection","c4:^obj","c4:obje","c4:bjec","c4:ject","c4:ecti","c4:ctio","c4:tion","c4:ion$","tok:social","c4:^soc","c4:soci","c4:ocia","c4:cial","c4:ial$","tok:selling","c4:^sel","c4:sell","c4:elli","c4:llin","c4:ling","c4:ing$"],
            &["tok:reflected","c4:^ref","c4:refl","c4:efle","c4:flec","c4:lect","c4:ecte","c4:cted","c4:ted$","tok:xss","c4:^xss","c4:xss$","tok:login","c4:^log","c4:logi","c4:ogin","c4:gin$","tok:form","c4:^for","c4:form","c4:orm$","tok:input","c4:^inp","c4:inpu","c4:nput","c4:put$","tok:field","c4:^fie","c4:fiel","c4:ield","c4:eld$"],
            &["tok:login","c4:^log","c4:logi","c4:ogin","c4:gin$","tok:form","c4:^for","c4:form","c4:orm$","tok:input","c4:^inp","c4:inpu","c4:nput","c4:put$","tok:validation","c4:^val","c4:vali","c4:alid","c4:lida","c4:idat","c4:dati","c4:atio","c4:tion","c4:ion$","tok:reflected","c4:^ref","c4:refl","c4:efle","c4:flec","c4:lect","c4:ecte","c4:cted","c4:ted$","tok:xss","c4:^xss","c4:xss$"],
        ];
        let features = raw.iter().map(|f| f.iter().map(|s| (*s).to_string()).collect()).collect();
        (ids, features)
    }

    fn feature_queries() -> Vec<Vec<String>> {
        let raw: &[&[&str]] = &[
            &["tok:session","c4:^ses","c4:sess","c4:essi","c4:ssio","c4:sion","c4:ion$","tok:resume","c4:^res","c4:resu","c4:esum","c4:sume","c4:ume$","tok:cortex","c4:^cor","c4:cort","c4:orte","c4:rtex","c4:tex$","tok:decoder","c4:^dec","c4:deco","c4:ecod","c4:code","c4:oder","c4:der$","tok:build","c4:^bui","c4:buil","c4:uild","c4:ild$","tok:plan","c4:^pla","c4:plan","c4:lan$"],
            &["tok:reflected","c4:^ref","c4:refl","c4:efle","c4:flec","c4:lect","c4:ecte","c4:cted","c4:ted$","tok:xss","c4:^xss","c4:xss$","tok:login","c4:^log","c4:logi","c4:ogin","c4:gin$","tok:input","c4:^inp","c4:inpu","c4:nput","c4:put$","tok:form","c4:^for","c4:form","c4:orm$"],
            &["tok:cold","c4:^col","c4:cold","c4:old$","tok:call","c4:^cal","c4:call","c4:all$","tok:objection","c4:^obj","c4:obje","c4:bjec","c4:ject","c4:ecti","c4:ctio","c4:tion","c4:ion$","tok:selling","c4:^sel","c4:sell","c4:elli","c4:llin","c4:ling","c4:ing$"],
            &["tok:absent","c4:^abs","c4:abse","c4:bsen","c4:sent","c4:ent$","tok:unrelated","c4:^unr","c4:unre","c4:nrel","c4:rela","c4:elat","c4:late","c4:ated","c4:ted$","tok:phrasing","c4:^phr","c4:phra","c4:hras","c4:rasi","c4:asin","c4:sing","c4:ing$","tok:here","c4:^her","c4:here","c4:ere$"],
        ];
        raw.iter().map(|f| f.iter().map(|s| (*s).to_string()).collect()).collect()
    }

    #[test]
    fn feature_contract_path_matches_js_oracle() {
        let (ids, item_features) = feature_corpus();
        let query_features = feature_queries();
        let index = build_index_from_features(&ids, &item_features, 0.2, true, false);
        // (qi, t, ids_sorted, total) — pinned from real-JS featureFn run.
        let oracle: &[(usize, f64, &[&str], usize)] = &[
            (0, 0.2, &["a", "b"], 2), (0, 0.3, &["a", "b"], 2), (0, 0.5, &["a", "b"], 2), (0, 0.7, &["a", "b"], 2),
            (1, 0.2, &["d", "e"], 2), (1, 0.3, &["d", "e"], 2), (1, 0.5, &["d", "e"], 2), (1, 0.7, &["d", "e"], 2),
            (2, 0.2, &["c"], 1), (2, 0.3, &["c"], 1), (2, 0.5, &["c"], 1), (2, 0.7, &[], 0),
            (3, 0.2, &[], 0), (3, 0.3, &[], 0), (3, 0.5, &[], 0), (3, 0.7, &[], 0),
        ];
        for &(qi, t, want_ids, total) in oracle {
            let want: Vec<String> = want_ids.iter().map(|s| (*s).to_string()).collect();
            let exact = match_exact_with_features(&index, &query_features[qi], t, 0);
            let prefix = match_prefix_filter_with_features(&index, &query_features[qi], t, 0);
            assert_eq!(sorted_ids(&exact.matches), want, "feat exact qi={qi} t={t}");
            assert_eq!(exact.total_above_threshold, total, "feat exact total qi={qi} t={t}");
            assert_eq!(sorted_ids(&prefix.matches), want, "feat prefix qi={qi} t={t}");
            assert_eq!(prefix.total_above_threshold, total, "feat prefix total qi={qi} t={t}");
            assert!(prefix.complete, "feat prefix complete qi={qi} t={t}");
        }
    }

    #[test]
    fn score_equals_threshold_is_inclusive_js_oracle() {
        // Boundary discriminator: an IDENTICAL item scores Jaccard == 1.0; at threshold 1.0 the JS
        // `score >= threshold` INCLUDES it. Pins the `>=` (not `>`) semantics against real-JS output
        // (verified: matchExact/matchPrefixFilter, t=1.0 → ids ["x"], total 1).
        let items = vec![
            CorpusItem { id: "x", text: "alpha beta gamma delta" },
            CorpusItem { id: "y", text: "alpha beta epsilon zeta" },
        ];
        let index = build_index(&items, 0.2, true, false);
        let q = "alpha beta gamma delta";
        let exact = match_exact(&index, q, 1.0, 0);
        let prefix = match_prefix_filter(&index, q, 1.0, 0);
        assert_eq!(sorted_ids(&exact.matches), vec!["x".to_string()], "exact t=1.0 inclusive");
        assert_eq!(exact.total_above_threshold, 1);
        assert_eq!(sorted_ids(&prefix.matches), vec!["x".to_string()], "prefix t=1.0 inclusive");
        assert_eq!(prefix.total_above_threshold, 1);
    }

    #[test]
    fn feature_contract_default_tokenize_equivalence() {
        // The serializable contract with the DEFAULT tokenizer features must equal the text path.
        let items = corpus();
        let ids: Vec<String> = items.iter().map(|i| i.id.to_string()).collect();
        let feature_sets: Vec<Vec<String>> =
            items.iter().map(|i| tokenize(i.text).tokens().to_vec()).collect();
        let text_index = build_index(&items, 0.2, true, false);
        let feat_index = build_index_from_features(&ids, &feature_sets, 0.2, true, false);
        let queries = ["reflected xss login input form", "subdomain dangling cname"];
        for q in queries {
            let qfeat = tokenize(q).tokens().to_vec();
            let a = match_exact(&text_index, q, 0.2, 0);
            let b = match_exact_with_features(&feat_index, &qfeat, 0.2, 0);
            assert_eq!(sorted_ids(&a.matches), sorted_ids(&b.matches), "equiv exact q={q}");
            let c = match_prefix_filter(&text_index, q, 0.2, 0);
            let d = match_prefix_filter_with_features(&feat_index, &qfeat, 0.2, 0);
            assert_eq!(sorted_ids(&c.matches), sorted_ids(&d.matches), "equiv prefix q={q}");
        }
    }
}
