//! nexus::ppmi — Rust port of the W4 "yuri-match matrix builds" from
//! `_SYSTEM/Scripts/math/yuri-token-expand.mjs` (+ `buildIdf` from `yuri-match-global-space.mjs`).
//!
//! Ported (Phase-2 deep wave, W4 GO set — matrix builds only):
//!   - `build_cooccurrence`  ← `buildCooccurrence`  [EXACT integer counts; structure-load-bearing]
//!   - `ppmi`                ← `ppmi`                [TRANSCENDENTAL log2; CAN return NaN at N=0]
//!   - `build_expansion_map` ← `buildExpansionMap`  [log2 + insertion-order tie-break, NO lexical tiebreak]
//!   - `build_idf`           ← `buildIdf`           [TRANSCENDENTAL log (natural) + V8 toFixed(12) round-trip]
//!
//! JS stays source-of-truth; this is delivery. Every vector pinned in `#[cfg(test)]` below was
//! generated by importing and CALLING the REAL JS function in node, never hand-computed (see the
//! oracle-command header in the test module).
//!
//! ── Conformance bar (00-MASTER-BRIEF §4/§5) ────────────────────────────────────────────────────
//! W4 yuri-match is **NOT gate-coupled** (advisory xref/circuitry/memory-match paths), so the bar
//! is the deck's general **1e-9 for floats** + EXACT for the integer/string structure. We TARGET and
//! ACHIEVE 0-ULP (bit-exact) on darwin-aarch64 anyway: V8 and the `libm` crate share the same fdlibm
//! fork there, so `libm::log2`/`libm::log` returned the *exact same bits* as V8 `Math.log2`/`Math.log`
//! for every pinned vector, and `format!("{:.12}")`+parse reproduced V8 `toFixed(12)→Number` exactly.
//!
//! ── Float-determinism discipline honored (00-MASTER-BRIEF §6/§6a) ───────────────────────────────
//!   - transcendentals via `libm::log2` / `libm::log` (pure-Rust fdlibm), NOT std method syntax.
//!   - f64 exclusively, no f32 paths; no `mul_add` — there is no `a*b+c` site in these kernels.
//!   - `-C target-feature=-fma` pinned crate-wide in `.cargo/config.toml`.
//!   - **`IndexMap` everywhere** (df / cooc / neigh) — V8 `Map` iterates in INSERTION order and that
//!     order is load-bearing: it drives `build_expansion_map`'s neighbor push order, and its stable
//!     sort has NO lexical tie-break, so equal-PPMI neighbors keep insertion order. Bare `HashMap`
//!     would scramble both. We replicate the JS exactly — we do NOT add a tiebreak (Phase-0 catch).
//!   - **NaN preserved, not guarded** — `ppmi` CAN return NaN at N=0 (`x/0` → NaN/Inf chains). The
//!     JS `Math.max(0, NaN)` returns NaN (Rust `f64::max` would return 0.0 → divergence), so we use
//!     a `js_max` that mirrors V8's NaN-propagating `Math.max` (Phase-0 catch).
//!   - **Co-occurrence key separator is `` (SOH, 0x01)**, not the empty string — the JS source
//!     renders it invisibly but it is `toks[i] + '' + toks[j]`. We use the same byte.
//!
//! ── Input contract (the tokenize boundary STAYS JS) ─────────────────────────────────────────────
//! `tokenize` (lowercase, split on `[^a-z0-9]+`, drop len<3, drop stop-words, 200k-char cap) is NOT
//! ported — it is a string kernel outside this matrix-build scope (see `staysJs`). `build_cooccurrence`
//! therefore takes **pre-tokenized** per-doc token arrays = the JS `[...tokenize(text)]` output
//! (insertion-ordered, de-duplicated by the Set). We replicate the in-function `.slice(0, cap).sort()`
//! and the `maxTokensPerDoc` clamp. Tokens are assumed to contain no `` byte (true for any
//! `tokenize` output, which is `[a-z0-9]` only) — a token containing `` would corrupt the key,
//! exactly as it would in the JS `key.split('')` round-trip in `build_expansion_map`.

use indexmap::IndexMap;

/// Co-occurrence key separator: V8 `Map` keys are `toks[i] + '' + toks[j]` (SOH, 0x01).
const COOC_SEP: char = '\u{0001}';

/// Co-occurrence statistics — mirror of the JS `{ df, cooc, N }` object.
/// `df`/`cooc` are `IndexMap` so iteration is INSERTION order, identical to V8 `Map`.
#[derive(Debug, Clone)]
pub struct CoocStats {
    /// term → document count (insertion order = first-seen order across docs, sorted-token order in-doc).
    pub df: IndexMap<String, u64>,
    /// "ab" (a < b within a doc's sorted tokens) → co-document count.
    pub cooc: IndexMap<String, u64>,
    /// document count.
    pub n: u64,
}

/// V8 `Math.max(0.0, x)` — NaN-PROPAGATING. `Math.max(0, NaN) === NaN`, whereas Rust `0.0.max(NaN)`
/// returns `0.0`. The PPMI `Math.max(0, log2(...))` must keep NaN, so we mirror V8 exactly.
#[inline]
fn js_max0(x: f64) -> f64 {
    if x.is_nan() {
        f64::NAN
    } else if x > 0.0 {
        x
    } else {
        0.0
    }
}

/// JS default `Array.prototype.sort()` for strings: compares by UTF-16 code unit, ascending, STABLE.
/// For `tokenize` output (`[a-z0-9]` ASCII only) this equals Rust's `str` `Ord` (UTF-8 byte order),
/// but we implement code-unit comparison so any pre-tokenized input is handled faithfully. V8's
/// default string sort is stable (ES2019+); `sort_by` is Rust's stable sort.
fn js_string_sort(tokens: &mut [String]) {
    tokens.sort_by(|a, b| {
        let mut ai = a.encode_utf16();
        let mut bi = b.encode_utf16();
        loop {
            match (ai.next(), bi.next()) {
                (Some(x), Some(y)) => {
                    if x != y {
                        return x.cmp(&y);
                    }
                }
                (None, Some(_)) => return std::cmp::Ordering::Less,
                (Some(_), None) => return std::cmp::Ordering::Greater,
                (None, None) => return std::cmp::Ordering::Equal,
            }
        }
    });
}

/// Resolve the `maxTokensPerDoc` cap exactly like the JS RED-TEAM clamp:
///   `Math.min(Number.isFinite(opt) && opt > 0 ? opt : 40, 200)`.
/// `None` / non-finite / ≤0 → default 40; any finite >0 value is `floor`ed implicitly by `.slice`
/// (JS `Array.prototype.slice` truncates a fractional length toward zero via ToIntegerOrInfinity).
fn resolve_cap(max_tokens_per_doc: Option<f64>) -> usize {
    let chosen = match max_tokens_per_doc {
        Some(v) if v.is_finite() && v > 0.0 => v,
        _ => 40.0,
    };
    // Math.min(chosen, 200)
    let capped = if chosen < 200.0 { chosen } else { 200.0 };
    // JS `.slice(0, len)` applies ToIntegerOrInfinity → truncate toward zero.
    capped.trunc() as usize
}

/// Port of `buildCooccurrence`. Takes **pre-tokenized** per-doc token arrays (the JS
/// `[...tokenize(text)]` output — insertion-ordered, de-duplicated). Replicates the in-function
/// `.slice(0, cap).sort()` and builds df + co-occurrence as insertion-ordered maps.
///
/// `max_tokens_per_doc` mirrors `opts.maxTokensPerDoc` (default 40, hard-clamped to 200).
pub fn build_cooccurrence(docs: &[Vec<String>], max_tokens_per_doc: Option<f64>) -> CoocStats {
    let cap = resolve_cap(max_tokens_per_doc);
    let mut df: IndexMap<String, u64> = IndexMap::new();
    let mut cooc: IndexMap<String, u64> = IndexMap::new();
    let n = docs.len() as u64;

    for doc in docs {
        // [...toks].slice(0, cap) — take the first `cap` tokens (insertion order preserved by caller).
        let take = doc.len().min(cap);
        let mut toks: Vec<String> = doc[..take].to_vec();
        // .sort() — JS default string sort (stable, UTF-16 code-unit order).
        js_string_sort(&mut toks);

        for i in 0..toks.len() {
            // df.set(toks[i], (df.get||0)+1)
            *df.entry(toks[i].clone()).or_insert(0) += 1;
            for j in (i + 1)..toks.len() {
                // key = toks[i] + '' + toks[j]  (toks already sorted → toks[i] <= toks[j])
                let mut key = String::with_capacity(toks[i].len() + 1 + toks[j].len());
                key.push_str(&toks[i]);
                key.push(COOC_SEP);
                key.push_str(&toks[j]);
                *cooc.entry(key).or_insert(0) += 1;
            }
        }
    }

    CoocStats { df, cooc, n }
}

/// Port of `ppmi(a, b, {df, cooc, N})`. PPMI(a,b) = max(0, log2[p(a,b)/(p(a)p(b))]).
///
/// EXACT replica of the JS branch structure, including its NaN behavior:
///   - `a === b` → 0
///   - `cooc.get(key) || 0`; `cab === 0` → 0  (also catches a missing key)
///   - `pa === 0 || pb === 0` → 0
///   - else `Math.max(0, Math.log2(pab / (pa * pb)))`
/// At N=0 with a present key, `pa = df/0` is NaN (0/0) or Inf, the `=== 0` guards are false, and the
/// final `Math.max(0, log2(...))` yields **NaN** — replicated, NOT guarded away (Phase-0 catch).
pub fn ppmi(a: &str, b: &str, stats: &CoocStats) -> f64 {
    if a == b {
        return 0.0;
    }
    // key = a < b ? a+SEP+b : b+SEP+a   — JS `<` is UTF-16 code-unit comparison.
    let key = build_cooc_key(a, b);
    let cab = *stats.cooc.get(&key).unwrap_or(&0); // cooc.get(key) || 0
    if cab == 0 {
        return 0.0;
    }
    let nf = stats.n as f64;
    let pa = (*stats.df.get(a).unwrap_or(&0) as f64) / nf; // (df.get(a)||0)/N
    let pb = (*stats.df.get(b).unwrap_or(&0) as f64) / nf;
    let pab = (cab as f64) / nf;
    if pa == 0.0 || pb == 0.0 {
        return 0.0;
    }
    js_max0(libm::log2(pab / (pa * pb)))
}

/// Build the `a < b ? a+SEP+b : b+SEP+a` co-occurrence key with V8 `<` (UTF-16 code-unit) semantics.
fn build_cooc_key(a: &str, b: &str) -> String {
    let (lo, hi) = if js_str_lt(a, b) { (a, b) } else { (b, a) };
    let mut key = String::with_capacity(lo.len() + 1 + hi.len());
    key.push_str(lo);
    key.push(COOC_SEP);
    key.push_str(hi);
    key
}

/// JS `a < b` for strings: UTF-16 code-unit lexicographic. Matches `js_string_sort`'s comparator.
fn js_str_lt(a: &str, b: &str) -> bool {
    let mut ai = a.encode_utf16();
    let mut bi = b.encode_utf16();
    loop {
        match (ai.next(), bi.next()) {
            (Some(x), Some(y)) => {
                if x != y {
                    return x < y;
                }
            }
            (None, Some(_)) => return true,  // a is a proper prefix of b → a < b
            (Some(_), None) => return false, // b is a proper prefix of a → a > b
            (None, None) => return false,    // equal → not <
        }
    }
}

/// Knobs for `build_expansion_map`, mirroring the JS destructured defaults
/// `{ minCooc = 3, ppmiFloor = 1.5, topN = 4 }`.
#[derive(Debug, Clone, Copy)]
pub struct ExpansionOpts {
    pub min_cooc: u64,
    pub ppmi_floor: f64,
    pub top_n: usize,
}

impl Default for ExpansionOpts {
    fn default() -> Self {
        ExpansionOpts { min_cooc: 3, ppmi_floor: 1.5, top_n: 4 }
    }
}

/// Port of `buildExpansionMap(stats, {minCooc, ppmiFloor, topN})`. term → top-N PPMI neighbors.
///
/// Replicates the JS exactly, including the **insertion-order tie-break with NO lexical tiebreak**
/// (Phase-0 catch): the comparator is purely `(x, y) => y.s - x.s`, and V8's `Array.sort` is stable,
/// so neighbors with equal PPMI keep the order in which they were pushed — which follows the `cooc`
/// IndexMap iteration (insertion) order. We do NOT add a lexical tiebreak.
///
/// The JS `arr.sort((x, y) => y.s - x.s)` treats a NaN comparator return as 0 (no reorder); our
/// stable sort with an `Equal` fallback on non-orderable pairs reproduces that "leave in place".
pub fn build_expansion_map(stats: &CoocStats, opts: ExpansionOpts) -> IndexMap<String, Vec<String>> {
    // neigh: term → [(neighborTerm, ppmiScore)] in push order.
    let mut neigh: IndexMap<String, Vec<(String, f64)>> = IndexMap::new();

    for (key, &c) in &stats.cooc {
        if c < opts.min_cooc {
            continue;
        }
        // const [a, b] = key.split('')  — split on the SOH separator, take first two parts.
        let mut parts = key.splitn(2, COOC_SEP);
        let a = parts.next().unwrap_or("");
        let b = parts.next().unwrap_or("");
        let s = ppmi(a, b, stats);
        // if (s < ppmiFloor) continue;   — note: NaN < x is false in JS too, so a NaN s is NOT skipped.
        if s < opts.ppmi_floor {
            continue;
        }
        // neigh(a).push({t:b,s}); neigh(b).push({t:a,s});
        neigh.entry(a.to_string()).or_default().push((b.to_string(), s));
        neigh.entry(b.to_string()).or_default().push((a.to_string(), s));
    }

    let mut map: IndexMap<String, Vec<String>> = IndexMap::new();
    for (term, arr) in &neigh {
        let mut sorted = arr.clone();
        // arr.sort((x, y) => y.s - x.s)  — descending by score, STABLE, no lexical tiebreak.
        // JS: a positive return swaps; equal/NaN return leaves order. We map (y.s - x.s) sign:
        //   y.s > x.s → positive → x after y → x is "Greater". So compare y vs x = x.s.cmp_desc.
        sorted.sort_by(|x, y| {
            // descending: y.s before x.s when y.s > x.s. Equivalent to comparing x.s and y.s desc.
            // total order that mirrors `y.s - x.s` sign with NaN→Equal (leave in place).
            match (y.1 - x.1).partial_cmp(&0.0) {
                Some(ord) => ord,
                None => std::cmp::Ordering::Equal, // NaN diff → JS treats as 0 → no reorder
            }
        });
        let out: Vec<String> = sorted.into_iter().take(opts.top_n).map(|(t, _)| t).collect();
        map.insert(term.clone(), out);
    }
    map
}

/// Port of `buildIdf`'s scoring line from `yuri-match-global-space.mjs`:
///   `idf.set(feature, Number((Math.log((1 + N) / (1 + count)) + 1).toFixed(12)))`
///
/// The `featureFn`/`tokenize`-driven df accumulation STAYS JS (string kernel out of scope); this takes
/// the **pre-computed** df entries (insertion order) + N and produces the idf map. Float bar: 1e-9
/// (W4 non-gate-coupled), but we reproduce V8 `Number(x.toFixed(12))` BIT-EXACT via `format!("{:.12}")`
/// + parse — verified equal on every pinned vector (incl. the round-half-to-even `toFixed` case).
pub fn build_idf(df_entries: &[(String, u64)], n: u64) -> IndexMap<String, f64> {
    let mut idf: IndexMap<String, f64> = IndexMap::new();
    let nf = n as f64;
    for (feature, count) in df_entries {
        // Math.log((1+N)/(1+count)) + 1   — natural log via libm.
        let raw = libm::log((1.0 + nf) / (1.0 + *count as f64)) + 1.0;
        idf.insert(feature.clone(), to_fixed_12_number(raw));
    }
    idf
}

/// V8 `Number(value.toFixed(12))`: format to 12 fractional decimal digits (round-half-to-even on the
/// underlying f64, like V8), then parse back (shortest-round-trip, like `Number(...)`).
///
/// `toFixed` is only defined for finite values with magnitude < 1e21; the idf inputs are always small
/// finite numbers, so the simple `format!("{:.12}")` path matches V8 exactly (verified). For a
/// non-finite input we return it unchanged (V8 `toFixed` would throw / "NaN"; idf never feeds one).
fn to_fixed_12_number(value: f64) -> f64 {
    if !value.is_finite() {
        return value;
    }
    let s = format!("{:.12}", value);
    s.parse::<f64>().unwrap_or(value)
}

// ===================================================================================================
#[cfg(test)]
mod tests {
    use super::*;

    // ===============================================================================================
    // ALL expected values below were generated by CALLING THE REAL JS in node, run from
    //   _SYSTEM/Scripts/math/  on 2026-06-14:
    //   node --input-type=module -e 'import {buildCooccurrence,ppmi,buildExpansionMap} from
    //      "./yuri-token-expand.mjs"; ...'
    //   (buildIdf line lifted verbatim from yuri-match-global-space.mjs).
    // Co-occurrence keys use the SOH () separator; nothing here is hand-computed.
    // Integers/strings EXACT; floats achieved 0-ULP on darwin-aarch64 (bar is 1e-9).
    // ===============================================================================================

    const BAR: f64 = 1e-9;

    fn close(got: f64, want: f64) {
        assert!(
            (got - want).abs() <= BAR,
            "got={got:?} want={want:?} diff={:?} bar={BAR:?}",
            (got - want).abs()
        );
    }

    fn doc(s: &str) -> Vec<String> {
        // Build a pre-tokenized doc that mirrors `[...tokenize(text)]` for these ASCII inputs:
        // tokenize lowercases, splits on non-[a-z0-9], drops len<3 + stop-words. The corpora below
        // use only len≥3 non-stop tokens, so a plain whitespace split reproduces the JS token array.
        s.split_whitespace().map(|t| t.to_string()).collect()
    }

    fn key(a: &str, b: &str) -> String {
        format!("{a}\u{0001}{b}")
    }

    // The "auth/signin" corpus — the demo corpus in yuri-token-expand.mjs, yields non-zero PPMI.
    fn auth_corpus() -> Vec<Vec<String>> {
        vec![
            doc("login requires password auth token"),
            doc("signin requires password auth token"),
            doc("login form auth credential check"),
            doc("signin form auth credential check"),
            doc("subdomain takeover dangling dns record"),
        ]
    }

    // ------------------------------ build_cooccurrence (EXACT) ------------------------------

    #[test]
    fn cooc_structure_corpus_a() {
        // corpusA = ["alpha beta gamma","beta gamma delta","alpha gamma delta epsilon"]
        let docs = vec![doc("alpha beta gamma"), doc("beta gamma delta"), doc("alpha gamma delta epsilon")];
        let s = build_cooccurrence(&docs, None);
        assert_eq!(s.n, 3);
        // A_DF=[["alpha",2],["beta",2],["gamma",3],["delta",2],["epsilon",1]] — insertion order
        let df: Vec<(&str, u64)> = s.df.iter().map(|(k, v)| (k.as_str(), *v)).collect();
        assert_eq!(
            df,
            vec![("alpha", 2), ("beta", 2), ("gamma", 3), ("delta", 2), ("epsilon", 1)]
        );
        // A_COOC (SOH keys), insertion order:
        // alpha|beta:1, alpha|gamma:2, beta|gamma:2, beta|delta:1, delta|gamma:2,
        // alpha|delta:1, alpha|epsilon:1, delta|epsilon:1, epsilon|gamma:1
        let cooc: Vec<(String, u64)> = s.cooc.iter().map(|(k, v)| (k.clone(), *v)).collect();
        assert_eq!(
            cooc,
            vec![
                (key("alpha", "beta"), 1),
                (key("alpha", "gamma"), 2),
                (key("beta", "gamma"), 2),
                (key("beta", "delta"), 1),
                (key("delta", "gamma"), 2),
                (key("alpha", "delta"), 1),
                (key("alpha", "epsilon"), 1),
                (key("delta", "epsilon"), 1),
                (key("epsilon", "gamma"), 1),
            ]
        );
    }

    #[test]
    fn cooc_cap_and_sort_trigger() {
        // longText = "zebra yankee xray whiskey victor", cap=3 → first 3 [zebra,yankee,xray] THEN sort
        //   → [xray,yankee,zebra]. DF insertion order = sorted order; cooc keys lexicographic.
        let docs = vec![doc("zebra yankee xray whiskey victor")];
        let s = build_cooccurrence(&docs, Some(3.0));
        let df: Vec<(&str, u64)> = s.df.iter().map(|(k, v)| (k.as_str(), *v)).collect();
        assert_eq!(df, vec![("xray", 1), ("yankee", 1), ("zebra", 1)]); // B_CAP3_DF
        let cooc: Vec<(String, u64)> = s.cooc.iter().map(|(k, v)| (k.clone(), *v)).collect();
        assert_eq!(
            cooc,
            vec![(key("xray", "yankee"), 1), (key("xray", "zebra"), 1), (key("yankee", "zebra"), 1)]
        ); // B_CAP3_COOC
    }

    #[test]
    fn cooc_cap_clamp_infinity_and_large() {
        // Math.min(Number.isFinite(opt)&&opt>0?opt:40, 200): Infinity→40, 1000→200, NaN/0/neg→40.
        assert_eq!(resolve_cap(Some(f64::INFINITY)), 40);
        assert_eq!(resolve_cap(Some(1000.0)), 200);
        assert_eq!(resolve_cap(Some(0.0)), 40);
        assert_eq!(resolve_cap(Some(-5.0)), 40);
        assert_eq!(resolve_cap(Some(f64::NAN)), 40);
        assert_eq!(resolve_cap(None), 40);
        assert_eq!(resolve_cap(Some(7.0)), 7);
        assert_eq!(resolve_cap(Some(7.9)), 7); // ToIntegerOrInfinity truncates toward zero
    }

    // ------------------------------------- ppmi -------------------------------------

    #[test]
    fn ppmi_auth_corpus_pins() {
        let s = build_cooccurrence(&auth_corpus(), None);
        // PPMI_ALL values from the real JS dump (a<b key reconstruction must match both arg orders):
        close(ppmi("auth", "login", &s), 0.32192809488736207);
        close(ppmi("login", "auth", &s), 0.32192809488736207); // reversed args → same
        close(ppmi("password", "requires", &s), 1.3219280948873622);
        close(ppmi("requires", "token", &s), 1.3219280948873622);
        close(ppmi("dangling", "dns", &s), 2.321928094887362);
        close(ppmi("subdomain", "takeover", &s), 2.321928094887362);
        // a===b → 0; missing pair → 0 (cab=0)
        assert_eq!(ppmi("login", "login", &s), 0.0);
        assert_eq!(ppmi("login", "zzz", &s), 0.0);
    }

    #[test]
    fn ppmi_zero_when_dense_corpus_a() {
        // corpusA produced all-zero PPMI (probabilities ≤ independence) — pin that path.
        let docs = vec![doc("alpha beta gamma"), doc("beta gamma delta"), doc("alpha gamma delta epsilon")];
        let s = build_cooccurrence(&docs, None);
        assert_eq!(ppmi("alpha", "gamma", &s), 0.0); // A_PPMI_alpha_gamma=0
        assert_eq!(ppmi("gamma", "alpha", &s), 0.0); // A_PPMI_gamma_alpha=0
        assert_eq!(ppmi("beta", "delta", &s), 0.0); // A_PPMI_beta_delta=0
    }

    #[test]
    fn ppmi_returns_nan_at_n_zero() {
        // C_PPMI_N0_isNaN=true — df present, N=0, key present → NaN (NOT guarded away).
        let mut df: IndexMap<String, u64> = IndexMap::new();
        df.insert("a".into(), 2);
        df.insert("b".into(), 3);
        let mut cooc: IndexMap<String, u64> = IndexMap::new();
        cooc.insert(key("a", "b"), 1);
        let s = CoocStats { df, cooc, n: 0 };
        assert!(ppmi("a", "b", &s).is_nan());
    }

    #[test]
    fn js_max0_propagates_nan() {
        // Guard against the Rust f64::max footgun: Math.max(0, NaN) === NaN.
        assert!(js_max0(f64::NAN).is_nan());
        assert_eq!(js_max0(-1.0), 0.0);
        assert_eq!(js_max0(2.5), 2.5);
        assert_eq!(js_max0(0.0), 0.0);
    }

    // ------------------------------- build_expansion_map -------------------------------

    #[test]
    fn expansion_map_corpus_a() {
        let docs = vec![doc("alpha beta gamma"), doc("beta gamma delta"), doc("alpha gamma delta epsilon")];
        let s = build_cooccurrence(&docs, None);
        // A_EXP (minCooc 2, ppmiFloor 0, topN 4):
        //   alpha:[gamma], gamma:[alpha,beta,delta], beta:[gamma], delta:[gamma]
        let map = build_expansion_map(&s, ExpansionOpts { min_cooc: 2, ppmi_floor: 0.0, top_n: 4 });
        let got: Vec<(String, Vec<String>)> = map.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
        assert_eq!(
            got,
            vec![
                ("alpha".into(), vec!["gamma".to_string()]),
                ("gamma".into(), vec!["alpha".to_string(), "beta".to_string(), "delta".to_string()]),
                ("beta".into(), vec!["gamma".to_string()]),
                ("delta".into(), vec!["gamma".to_string()]),
            ]
        );
    }

    #[test]
    fn expansion_map_topn_truncation() {
        let docs = vec![doc("alpha beta gamma"), doc("beta gamma delta"), doc("alpha gamma delta epsilon")];
        let s = build_cooccurrence(&docs, None);
        // A_EXP_topN1: alpha:[gamma], gamma:[alpha], beta:[gamma], delta:[gamma]
        let map = build_expansion_map(&s, ExpansionOpts { min_cooc: 2, ppmi_floor: 0.0, top_n: 1 });
        assert_eq!(map.get("gamma").unwrap(), &vec!["alpha".to_string()]);
        assert_eq!(map.get("alpha").unwrap(), &vec!["gamma".to_string()]);
    }

    #[test]
    fn expansion_map_defaults_empty() {
        // Default knobs (minCooc 3, ppmiFloor 1.5) on the auth corpus → empty (A_EXP defaults = []).
        let s = build_cooccurrence(&auth_corpus(), None);
        let map = build_expansion_map(&s, ExpansionOpts::default());
        assert!(map.is_empty());
    }

    #[test]
    fn expansion_map_tie_break_is_insertion_order() {
        // Construct three neighbors of "x" with EQUAL ppmi; the stable sort (NO lexical tiebreak)
        // must keep cooc-insertion order. Real-JS oracle: ["z","m","n"].
        // df all 2, N=4 → ppmi(x,*) all equal; cooc inserted x|z, m|x, n|x.
        let mut df: IndexMap<String, u64> = IndexMap::new();
        for t in ["x", "m", "n", "z"] {
            df.insert(t.into(), 2);
        }
        let mut cooc: IndexMap<String, u64> = IndexMap::new();
        cooc.insert(key("x", "z"), 2); // x<z → x|z
        cooc.insert(key("m", "x"), 2); // m<x → m|x
        cooc.insert(key("n", "x"), 2); // n<x → n|x
        let s = CoocStats { df, cooc, n: 4 };
        let map = build_expansion_map(&s, ExpansionOpts { min_cooc: 2, ppmi_floor: 0.0, top_n: 4 });
        assert_eq!(map.get("x").unwrap(), &vec!["z".to_string(), "m".to_string(), "n".to_string()]);
    }

    // ----------------------------------- build_idf -----------------------------------

    #[test]
    fn idf_pins() {
        // D_IDF_N5 = [["auth",1.182321556794],["login",1.69314718056],
        //             ["dangling",2.098612288668],["x",2.791759469228]]
        let df = vec![
            ("auth".to_string(), 4u64),
            ("login".to_string(), 2),
            ("dangling".to_string(), 1),
            ("x".to_string(), 0),
        ];
        let idf = build_idf(&df, 5);
        close(*idf.get("auth").unwrap(), 1.182321556794);
        close(*idf.get("login").unwrap(), 1.69314718056);
        close(*idf.get("dangling").unwrap(), 2.098612288668);
        close(*idf.get("x").unwrap(), 2.791759469228);
        // insertion order preserved
        let keys: Vec<&str> = idf.keys().map(|k| k.as_str()).collect();
        assert_eq!(keys, vec!["auth", "login", "dangling", "x"]);
    }

    #[test]
    fn idf_more_pins() {
        // D_IDF_N100 = [["a",4.921973336281],["b",1.683294884117],["c",1]]
        let idf = build_idf(
            &[("a".to_string(), 1u64), ("b".to_string(), 50), ("c".to_string(), 100)],
            100,
        );
        close(*idf.get("a").unwrap(), 4.921973336281);
        close(*idf.get("b").unwrap(), 1.683294884117); // the round-half-to-even toFixed case
        close(*idf.get("c").unwrap(), 1.0);
        // D_IDF_countGTn = [["x",-0.29928298413]]  (count > N → negative idf)
        let idf2 = build_idf(&[("x".to_string(), 10u64)], 2);
        close(*idf2.get("x").unwrap(), -0.29928298413);
        // D_IDF_N0 = [["x",1]]  (N=0, count=0 → log(1/1)+1 = 1)
        let idf3 = build_idf(&[("x".to_string(), 0u64)], 0);
        close(*idf3.get("x").unwrap(), 1.0);
    }

    // ------------------------ 0-ULP transcendental conformance ------------------------

    #[test]
    fn log2_log_bit_exact_vs_v8() {
        // Raw transcendental bits, pinned from V8 (Math.log2 / Math.log) — exercises the libm fdlibm
        // fork == V8 fdlibm fork on darwin-aarch64 (0-ULP, not just ≤1e-9).
        assert_eq!(libm::log2(1.25_f64), 0.32192809488736235);
        assert_eq!(libm::log2(2.5_f64), 1.3219280948873624);
        assert_eq!(libm::log(0.6_f64), -0.5108256237659907);
        assert_eq!(libm::log(3.0_f64 / 11.0), -1.2992829841302609);
    }

    #[test]
    fn to_fixed_12_matches_v8() {
        // V8 Number(x.toFixed(12)) round-trips — incl. the round-half-to-even quirk.
        assert_eq!(to_fixed_12_number(1.1823215567939547), 1.182321556794);
        assert_eq!(to_fixed_12_number(-0.2992829841302609), -0.29928298413);
        assert_eq!(to_fixed_12_number(1.6832948841169337), 1.683294884117);
        assert_eq!(to_fixed_12_number(1.0), 1.0);
    }

    #[test]
    fn js_string_sort_matches_default_sort() {
        // JS default Array.sort() string order is stable, code-unit ascending.
        let mut v: Vec<String> = ["zebra", "yankee", "xray"].iter().map(|s| s.to_string()).collect();
        js_string_sort(&mut v);
        assert_eq!(v, vec!["xray".to_string(), "yankee".to_string(), "zebra".to_string()]);
        // numerics sort before letters by code unit ('0'..'9' < 'a'..'z')
        let mut v2: Vec<String> = ["b2", "a1", "10", "9z"].iter().map(|s| s.to_string()).collect();
        js_string_sort(&mut v2);
        assert_eq!(v2, vec!["10".to_string(), "9z".to_string(), "a1".to_string(), "b2".to_string()]);
    }
}
