//! nexus_core::stats — Rust port of the W1 "clean stats" set from `_SYSTEM/Scripts/math/math-kernel.mjs`.
//!
//! Ported (Phase-1, W1 GO set): `rankWithTies`, `median`, `percentile`, `weightedVariance`.
//! JS stays source-of-truth; this is delivery. Every vector pinned in `#[cfg(test)]` below was
//! generated by importing and CALLING the REAL JS function in node, never hand-computed.
//!
//! Conformance bar (these kernels are NOT gate/prover-coupled per 01-PORT-SPECS §W1): integers EXACT,
//! floats ≤ 1e-9 — which absorbs `roundStable` (V8 `toPrecision(15)→Number`), so `round_stable` here is
//! a faithful close approximation, not a bit-exact replica.
//!
//! Float-determinism discipline honored (00-MASTER-BRIEF §6/§6a):
//!   - f64 exclusively, no f32 paths.
//!   - no `mul_add` — every fused site is written `(a*b)+c`.
//!   - stable `sort_by` + `f64::total_cmp` for the value sorts (NaN excluded upstream by the finite guard).
//!   - NaN/-0 canonicalized at the kernel boundary (`canon`).
//!   - no `HashMap` here (no order-dependent map output).
//!
//! Edge-case policy mirror: the JS throws on empty / non-finite / length-mismatch / bad-weight inputs.
//! Rust mirrors this with a `StatsError` `Result` (no panics), with messages byte-identical to the JS
//! `Error.message` strings so a downstream conformance harness can compare them exactly.

/// Magnitude below which `round_stable` snaps to 0. Mirrors the JS kernel `EPSILON = 1e-12`.
const EPSILON: f64 = 1e-12;

/// Error mirror of the JS kernel's thrown `Error` strings. The `message()` text is byte-identical to
/// the JS reference so a conformance harness can assert error parity exactly.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StatsError {
    /// `<label> must be a non-empty array` / `... must be a finite number` etc. — carries the exact text.
    Message(String),
}

impl StatsError {
    pub fn message(&self) -> &str {
        match self {
            StatsError::Message(s) => s,
        }
    }
}

impl std::fmt::Display for StatsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.message())
    }
}

impl std::error::Error for StatsError {}

pub type StatsResult<T> = Result<T, StatsError>;

fn err<T>(msg: impl Into<String>) -> StatsResult<T> {
    Err(StatsError::Message(msg.into()))
}

/// Canonicalize a boundary float: quiet-NaN canonical, -0.0 → +0.0. Mirrors V8's `-0 === 0` and the
/// canonical quiet NaN (00-MASTER-BRIEF §6 NaN/-0 trap). Used on float RETURN values; inputs are
/// validated finite upstream so this only ever normalizes a -0.0 result to +0.0.
#[inline]
fn canon(x: f64) -> f64 {
    if x.is_nan() {
        f64::NAN
    } else if x == 0.0 {
        // catches both +0.0 and -0.0 (they compare equal); force +0.0
        0.0
    } else {
        x
    }
}

/// V8 `roundStable`: `!isFinite → value`; `|value| < EPSILON → 0`; else `Number(value.toPrecision(15))`.
///
/// The 1e-9 conformance bar absorbs this, so an exact V8 Grisu/Ryu replica is not required — only a
/// close 15-significant-figure round. We snap-to-zero below EPSILON (exact, matches JS), then round to
/// 15 significant figures via decimal-string round-trip (`format!("{:.*e}")` rounds half-to-even like
/// V8's `toPrecision`, and Rust's float parser is shortest-round-trip like V8's `Number`). The result
/// stays well inside 1e-9 of the JS value for all in-range magnitudes.
fn round_stable(value: f64) -> f64 {
    if !value.is_finite() {
        return value;
    }
    if value.abs() < EPSILON {
        return 0.0;
    }
    // 15 significant figures == (15 - 1) digits after the decimal point in scientific notation,
    // mirroring JS `toPrecision(15)` (which keeps 15 significant digits). Parse back like `Number(...)`.
    let s = format!("{:.*e}", 15 - 1, value);
    canon(s.parse::<f64>().unwrap_or(value))
}

// ---------------------------------------------------------------------------
// validation helpers — mirror math-kernel.mjs assert* functions (same messages)
// ---------------------------------------------------------------------------

/// Mirror of `assertNumberArray(values, label)`: non-empty + every entry a finite number.
/// In Rust the slice is already `f64`, so the only runtime checks are non-empty + finite.
fn assert_number_array(values: &[f64], label: &str) -> StatsResult<()> {
    if values.is_empty() {
        return err(format!("{label} must be a non-empty array"));
    }
    for &value in values {
        if !value.is_finite() {
            return err(format!("{label} must be a finite number"));
        }
    }
    Ok(())
}

/// Mirror of `assertFiniteNumber(value, label)`.
fn assert_finite_number(value: f64, label: &str) -> StatsResult<()> {
    if !value.is_finite() {
        return err(format!("{label} must be a finite number"));
    }
    Ok(())
}

/// Mirror of `assertSameLength(left, right, label)`.
fn assert_same_length(left: &[f64], right: &[f64], label: &str) -> StatsResult<()> {
    if left.len() != right.len() {
        return err(format!("{label} requires distributions of equal length"));
    }
    Ok(())
}

/// Mirror of `assertVectorPair(left, right, label)`: both finite non-empty arrays + equal length.
fn assert_vector_pair(left: &[f64], right: &[f64], label: &str) -> StatsResult<()> {
    assert_number_array(left, &format!("{label} left"))?;
    assert_number_array(right, &format!("{label} right"))?;
    assert_same_length(left, right, label)
}

/// Mirror of `assertWeightVector(weights)`: non-negative entries, strictly positive sum; returns sum.
/// Sum uses a scalar left-fold (matches the JS `for..of` accumulation; no SIMD reduction reorder).
fn assert_weight_vector(weights: &[f64]) -> StatsResult<f64> {
    let mut total = 0.0_f64;
    for &weight in weights {
        if weight < 0.0 {
            return err("weights must be non-negative");
        }
        total += weight;
    }
    if total <= 0.0 {
        return err("weights must have a positive sum");
    }
    Ok(total)
}

/// Mirror of `assertFiniteResult(value, label)`: fail-closed on a non-finite aggregate (overflow).
fn assert_finite_result(value: f64, label: &str) -> StatsResult<f64> {
    if !value.is_finite() {
        return err(format!("{label} is non-finite (aggregate overflow)"));
    }
    Ok(value)
}

/// Ascending stable sort of a float slice using `total_cmp` (NaN excluded upstream). Returns a sorted
/// copy, mirroring the JS `[...values].sort((a, b) => a - b)` (non-mutating, stable for ties).
fn sorted_asc(values: &[f64]) -> Vec<f64> {
    let mut s = values.to_vec();
    s.sort_by(f64::total_cmp);
    s
}

// ---------------------------------------------------------------------------
// W1 clean stats set
// ---------------------------------------------------------------------------

/// `rankWithTies(arr)` — average ranks over tie blocks (1-based positions). EXACT integer/half-integer
/// output (no `round_stable`). Stable sort by value preserves original index order within a tie block,
/// matching the JS `[v, i]` pair sort (JS `Array.prototype.sort` is stable, ES2019+).
pub fn rank_with_ties(arr: &[f64]) -> StatsResult<Vec<f64>> {
    assert_number_array(arr, "rankWithTies input")?;
    // (value, original_index) pairs, stably sorted by value ascending.
    let mut idx: Vec<(f64, usize)> = arr.iter().copied().enumerate().map(|(i, v)| (v, i)).collect();
    idx.sort_by(|a, b| a.0.total_cmp(&b.0));

    let mut r = vec![0.0_f64; arr.len()];
    let mut i = 0usize;
    while i < idx.len() {
        let mut j = i;
        while j + 1 < idx.len() && idx[j + 1].0 == idx[i].0 {
            j += 1;
        }
        // mean of the tied block's 1-based positions i+1..=j+1  ==  (i + j + 2) / 2
        let avg = (i as f64 + j as f64 + 2.0) / 2.0;
        for k in i..=j {
            r[idx[k].1] = avg;
        }
        i = j + 1;
    }
    Ok(r)
}

/// `median(values)` — averaged-middle convention; `round_stable` applied. Kernel-strict on non-finite.
pub fn median(values: &[f64]) -> StatsResult<f64> {
    assert_number_array(values, "median input")?;
    let s = sorted_asc(values);
    let m = s.len() / 2; // Math.floor(len/2) for non-negative len
    let raw = if s.len() % 2 == 1 {
        s[m]
    } else {
        (s[m - 1] + s[m]) / 2.0
    };
    Ok(round_stable(raw))
}

/// `percentile(values, p)` — nearest-rank (ceil) convention: `sorted[ceil(p/100·n) − 1]`, no
/// interpolation. `p ∈ (0, 100]` or throws. `round_stable` applied.
pub fn percentile(values: &[f64], p: f64) -> StatsResult<f64> {
    assert_finite_number(p, "percentile")?;
    if p <= 0.0 || p > 100.0 {
        return err("percentile p must be in (0, 100]");
    }
    assert_number_array(values, "percentile input")?;
    let s = sorted_asc(values);
    // Math.ceil((p/100) * n) - 1. n >= 1 and p in (0,100] => rank in [1, n] => index in [0, n-1].
    let rank = ((p / 100.0) * s.len() as f64).ceil();
    let index = (rank as i64 - 1) as usize;
    Ok(round_stable(s[index]))
}

/// Internal `weightedMean(values, weights)` — needed by `weighted_variance`. Fail-closed on a
/// non-finite aggregate. Scalar left-fold matches the JS `reduce` accumulation order.
fn weighted_mean(values: &[f64], weights: &[f64]) -> StatsResult<f64> {
    assert_vector_pair(values, weights, "weighted mean")?;
    let weight_sum = assert_weight_vector(weights)?;
    let mut acc = 0.0_f64;
    for i in 0..values.len() {
        acc += values[i] * weights[i]; // (a*b)+c via separate ops; no mul_add
    }
    let mean = acc / weight_sum;
    Ok(round_stable(assert_finite_result(mean, "weighted mean")?))
}

/// `weightedVariance(values, weights)` — population (biased) form, divides by the raw weight sum.
/// Note: mirrors the JS exactly, which computes the mean via `weightedMean` (so the mean is itself
/// `round_stable`-quantized BEFORE the deviation sum), then `round_stable`s the variance.
pub fn weighted_variance(values: &[f64], weights: &[f64]) -> StatsResult<f64> {
    assert_vector_pair(values, weights, "weighted variance")?;
    let weight_sum = assert_weight_vector(weights)?;
    let mean = weighted_mean(values, weights)?;
    let mut acc = 0.0_f64;
    for i in 0..values.len() {
        let d = values[i] - mean;
        acc += weights[i] * (d * d); // (value - mean)**2, then * weight; (a*b)+c, no mul_add
    }
    let var = acc / weight_sum;
    Ok(round_stable(assert_finite_result(var, "weighted variance")?))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ===================================================================================
    // ALL expected values below were generated by CALLING THE REAL JS in node:
    //   node -e 'import("./math-kernel.mjs").then(m=>console.log(JSON.stringify(...)))'
    // run from _SYSTEM/Scripts/math/ on 2026-06-14. Integers/strings EXACT; floats ≤ 1e-9.
    // The exact harness output is pinned verbatim in the assertions; nothing hand-computed.
    // ===================================================================================

    /// Float conformance bar for these (non-gate-coupled) kernels.
    const BAR: f64 = 1e-9;

    fn close(got: f64, want: f64) {
        assert!(
            (got - want).abs() <= BAR,
            "got={got:?} want={want:?} diff={:?} bar={BAR:?}",
            (got - want).abs()
        );
    }

    fn close_vec(got: &[f64], want: &[f64]) {
        assert_eq!(got.len(), want.len(), "length mismatch got={got:?} want={want:?}");
        for (g, w) in got.iter().zip(want.iter()) {
            close(*g, *w);
        }
    }

    // ----------------------------- rankWithTies -----------------------------
    // rankWithTies output is EXACT (integers / half-integers), so assert exact f64 equality.

    #[test]
    fn rank_with_ties_pins() {
        assert_eq!(rank_with_ties(&[5.0]).unwrap(), vec![1.0]); // rank_singleton
        assert_eq!(rank_with_ties(&[3.0, 1.0, 2.0, 4.0]).unwrap(), vec![3.0, 1.0, 2.0, 4.0]); // rank_even
        assert_eq!(rank_with_ties(&[3.0, 1.0, 2.0]).unwrap(), vec![3.0, 1.0, 2.0]); // rank_odd
        assert_eq!(rank_with_ties(&[7.0, 7.0, 7.0, 7.0]).unwrap(), vec![2.5, 2.5, 2.5, 2.5]); // all_equal
        assert_eq!(
            rank_with_ties(&[-1.0, -5.0, -3.0, -5.0, -1.0]).unwrap(),
            vec![4.5, 1.5, 3.0, 1.5, 4.5]
        ); // rank_negative
        assert_eq!(
            rank_with_ties(&[10.0, 20.0, 20.0, 30.0, 30.0, 30.0, 40.0]).unwrap(),
            vec![1.0, 2.5, 2.5, 5.0, 5.0, 5.0, 7.0]
        ); // rank_tie_blocks
        assert_eq!(
            rank_with_ties(&[1.0, 1.0, 2.0, 2.0, 3.0, 3.0]).unwrap(),
            vec![1.5, 1.5, 3.5, 3.5, 5.5, 5.5]
        ); // rank_dup_pairs
        assert_eq!(
            rank_with_ties(&[5.0, 1.0, 5.0, 1.0, 5.0]).unwrap(),
            vec![4.0, 1.5, 4.0, 1.5, 4.0]
        ); // rank_unsorted_ties
    }

    #[test]
    fn rank_with_ties_empty_throws() {
        let e = rank_with_ties(&[]).unwrap_err();
        assert_eq!(e.message(), "rankWithTies input must be a non-empty array");
    }

    // ------------------------------- median --------------------------------

    #[test]
    fn median_pins() {
        close(median(&[42.0]).unwrap(), 42.0); // singleton
        close(median(&[1.0, 2.0, 3.0, 4.0]).unwrap(), 2.5); // even
        close(median(&[3.0, 1.0, 2.0]).unwrap(), 2.0); // odd
        close(median(&[8.0, 8.0, 8.0]).unwrap(), 8.0); // all_equal
        close(median(&[-10.0, -20.0, -30.0, -40.0]).unwrap(), -25.0); // negative
        close(median(&[1.5, 2.5, -3.5, 4.25]).unwrap(), 2.0); // mixed
        close(median(&[1.0, 2.0]).unwrap(), 1.5); // two
        close(median(&[9.0, 1.0, 5.0, 3.0, 7.0]).unwrap(), 5.0); // unsorted
    }

    #[test]
    fn median_empty_throws() {
        let e = median(&[]).unwrap_err();
        assert_eq!(e.message(), "median input must be a non-empty array");
    }

    // ----------------------------- percentile ------------------------------

    #[test]
    fn percentile_pins() {
        close(percentile(&[1.0, 2.0, 3.0, 4.0], 50.0).unwrap(), 2.0); // p50_even
        close(percentile(&[1.0, 2.0, 3.0, 4.0, 5.0], 50.0).unwrap(), 3.0); // p50_odd
        close(percentile(&[1.0, 2.0, 3.0, 4.0, 5.0], 100.0).unwrap(), 5.0); // p100
        close(percentile(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], 25.0).unwrap(), 2.0); // p25
        close(percentile(&[99.0], 50.0).unwrap(), 99.0); // singleton
        close(percentile(&[-5.0, -1.0, -3.0, -2.0, -4.0], 75.0).unwrap(), -2.0); // negative
        close(
            percentile(&[10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0], 1.0).unwrap(),
            10.0,
        ); // p1 (ceil(0.01*10)=1 -> index 0)
    }

    #[test]
    fn percentile_boundary_throws() {
        // p=0 throws (the spec-required p=0 boundary case)
        assert_eq!(
            percentile(&[1.0, 2.0, 3.0], 0.0).unwrap_err().message(),
            "percentile p must be in (0, 100]"
        );
        // p<0 throws
        assert_eq!(
            percentile(&[1.0, 2.0, 3.0], -5.0).unwrap_err().message(),
            "percentile p must be in (0, 100]"
        );
        // p>100 throws
        assert_eq!(
            percentile(&[1.0, 2.0, 3.0], 101.0).unwrap_err().message(),
            "percentile p must be in (0, 100]"
        );
        // empty values throws (p valid, validated after p-range per JS order)
        assert_eq!(
            percentile(&[], 50.0).unwrap_err().message(),
            "percentile input must be a non-empty array"
        );
    }

    // -------------------------- weightedVariance ---------------------------

    #[test]
    fn weighted_variance_pins() {
        close(weighted_variance(&[5.0], &[1.0]).unwrap(), 0.0); // singleton
        close(weighted_variance(&[1.0, 2.0, 3.0, 4.0], &[1.0, 1.0, 1.0, 1.0]).unwrap(), 1.25); // uniform
        close(weighted_variance(&[1.0, 2.0, 3.0, 4.0], &[1.0, 2.0, 3.0, 4.0]).unwrap(), 1.0); // weighted
        close(weighted_variance(&[5.0, 5.0, 5.0], &[2.0, 3.0, 1.0]).unwrap(), 0.0); // all_equal
        close(weighted_variance(&[-1.0, -2.0, -3.0], &[1.0, 1.0, 1.0]).unwrap(), 0.666666666666667); // negative
        close(weighted_variance(&[10.0, 20.0, 30.0], &[0.1, 0.2, 0.7]).unwrap(), 44.0); // fractional_w
        close(weighted_variance(&[1.0, 2.0, 3.0], &[0.0, 1.0, 0.0]).unwrap(), 0.0); // zero_weight
    }

    #[test]
    fn weighted_variance_guard_throws() {
        assert_eq!(
            weighted_variance(&[], &[]).unwrap_err().message(),
            "weighted variance left must be a non-empty array"
        );
        assert_eq!(
            weighted_variance(&[1.0, 2.0], &[1.0]).unwrap_err().message(),
            "weighted variance requires distributions of equal length"
        );
        assert_eq!(
            weighted_variance(&[1.0, 2.0], &[1.0, -1.0]).unwrap_err().message(),
            "weights must be non-negative"
        );
        assert_eq!(
            weighted_variance(&[1.0, 2.0], &[0.0, 0.0]).unwrap_err().message(),
            "weights must have a positive sum"
        );
    }

    // ------------------------- round_stable behavior -----------------------

    #[test]
    fn round_stable_snaps_and_passes_through() {
        assert_eq!(round_stable(5e-13), 0.0); // |x| < EPSILON -> 0
        assert_eq!(round_stable(0.0), 0.0);
        assert!(round_stable(f64::INFINITY).is_infinite()); // non-finite passes through
        assert!(round_stable(f64::NAN).is_nan());
        // 15-sig-fig round stays within the 1e-9 bar of the JS value
        close(round_stable(0.6666666666666666), 0.666666666666667);
        // -0.0 result canonicalizes to +0.0 (no negative-zero leakage)
        assert!(round_stable(-0.0).to_bits() == 0u64);
    }

    // ----------------- close_vec helper is exercised above -----------------
    #[test]
    fn close_vec_smoke() {
        close_vec(&rank_with_ties(&[2.0, 2.0]).unwrap(), &[1.5, 1.5]);
    }
}
